/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public MenuInicio() {
        initComponents();
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Registros,btn_Consultas,btn_Modificar}, new JPanel[]{ind_2,ind_3, ind_4});
        setLocationRelativeTo(null);
        Transparencia();
    }

    public void Transparencia() {
        AgregarUsuario.setOpaque(false);
        AgregarUsuario.setContentAreaFilled(false);
        AgregarUsuario.setBorderPainted(false);
        BorrarUsuario.setOpaque(false);
        BorrarUsuario.setContentAreaFilled(false);
        BorrarUsuario.setBorderPainted(false);
        ConfigUsuario.setOpaque(false);
        ConfigUsuario.setContentAreaFilled(false);
        ConfigUsuario.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Lateral = new javax.swing.JPanel();
        btn_Inicio = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_Registros = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_Consultas = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        btn_Modificar = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Barra_Superior = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        Panel_Central = new javax.swing.JPanel();
        Central1 = new javax.swing.JPanel();
        Central2 = new javax.swing.JPanel();
        AgregarUsuario = new javax.swing.JButton();
        BorrarUsuario = new javax.swing.JButton();
        ConfigUsuario = new javax.swing.JButton();
        Central3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Central4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(23, 35, 51));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Inicio.setBackground(new java.awt.Color(23, 35, 51));
        btn_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InicioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");

        javax.swing.GroupLayout btn_InicioLayout = new javax.swing.GroupLayout(btn_Inicio);
        btn_Inicio.setLayout(btn_InicioLayout);
        btn_InicioLayout.setHorizontalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        btn_InicioLayout.setVerticalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, -1));

        btn_Registros.setBackground(new java.awt.Color(23, 35, 51));
        btn_Registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_RegistrosMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modificar");

        javax.swing.GroupLayout btn_RegistrosLayout = new javax.swing.GroupLayout(btn_Registros);
        btn_Registros.setLayout(btn_RegistrosLayout);
        btn_RegistrosLayout.setHorizontalGroup(
            btn_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_RegistrosLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        btn_RegistrosLayout.setVerticalGroup(
            btn_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_RegistrosLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_RegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, -1));

        btn_Consultas.setBackground(new java.awt.Color(23, 35, 51));
        btn_Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ConsultasMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");

        javax.swing.GroupLayout btn_ConsultasLayout = new javax.swing.GroupLayout(btn_Consultas);
        btn_Consultas.setLayout(btn_ConsultasLayout);
        btn_ConsultasLayout.setHorizontalGroup(
            btn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Usuario)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        btn_ConsultasLayout.setVerticalGroup(
            btn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, -1));

        btn_Modificar.setBackground(new java.awt.Color(23, 35, 51));
        btn_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ModificarMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Consultas");

        javax.swing.GroupLayout btn_ModificarLayout = new javax.swing.GroupLayout(btn_Modificar);
        btn_Modificar.setLayout(btn_ModificarLayout);
        btn_ModificarLayout.setHorizontalGroup(
            btn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        btn_ModificarLayout.setVerticalGroup(
            btn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, -1));

        getContentPane().add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 590));

        Barra_Superior.setBackground(new java.awt.Color(12, 129, 129));
        Barra_Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMouseDragged(evt);
            }
        });
        Barra_Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMousePressed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Barra_SuperiorLayout = new javax.swing.GroupLayout(Barra_Superior);
        Barra_Superior.setLayout(Barra_SuperiorLayout);
        Barra_SuperiorLayout.setHorizontalGroup(
            Barra_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra_SuperiorLayout.createSequentialGroup()
                .addContainerGap(683, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        Barra_SuperiorLayout.setVerticalGroup(
            Barra_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_SuperiorLayout.createSequentialGroup()
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(Barra_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 50));

        Panel_Central.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Central1Layout = new javax.swing.GroupLayout(Central1);
        Central1.setLayout(Central1Layout);
        Central1Layout.setHorizontalGroup(
            Central1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        Central1Layout.setVerticalGroup(
            Central1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        AgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddUser 1.png"))); // NOI18N
        AgregarUsuario.setBorderPainted(false);
        AgregarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddUser 2.png"))); // NOI18N

        BorrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BorrarUser1.png"))); // NOI18N
        BorrarUsuario.setBorderPainted(false);
        BorrarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BorrarUser 2.png"))); // NOI18N

        ConfigUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config 1.png"))); // NOI18N
        ConfigUsuario.setBorderPainted(false);
        ConfigUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config 2.png"))); // NOI18N

        javax.swing.GroupLayout Central2Layout = new javax.swing.GroupLayout(Central2);
        Central2.setLayout(Central2Layout);
        Central2Layout.setHorizontalGroup(
            Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarUsuario)
                    .addComponent(ConfigUsuario))
                .addGap(46, 46, 46)
                .addComponent(BorrarUsuario)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Central2Layout.setVerticalGroup(
            Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarUsuario)
                    .addGroup(Central2Layout.createSequentialGroup()
                        .addComponent(AgregarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfigUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AgregarUsuario.getAccessibleContext().setAccessibleName("AgregarUsuario");
        BorrarUsuario.getAccessibleContext().setAccessibleName("BorrarUsuario");
        ConfigUsuario.getAccessibleContext().setAccessibleName("ConfigUsuario");

        jLabel3.setText("PANEL CONSULTAS");

        javax.swing.GroupLayout Central3Layout = new javax.swing.GroupLayout(Central3);
        Central3.setLayout(Central3Layout);
        Central3Layout.setHorizontalGroup(
            Central3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        Central3Layout.setVerticalGroup(
            Central3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central3Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jLabel4.setText("PANEL MODIFICAR");

        javax.swing.GroupLayout Central4Layout = new javax.swing.GroupLayout(Central4);
        Central4.setLayout(Central4Layout);
        Central4Layout.setHorizontalGroup(
            Central4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Central4Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        Central4Layout.setVerticalGroup(
            Central4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central4Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_CentralLayout = new javax.swing.GroupLayout(Panel_Central);
        Panel_Central.setLayout(Panel_CentralLayout);
        Panel_CentralLayout.setHorizontalGroup(
            Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Central1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_CentralLayout.setVerticalGroup(
            Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Central1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 720, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InicioMousePressed
        // TODO add your handling code here:
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Registros,btn_Consultas,btn_Modificar}, new JPanel[]{ind_2,ind_3, ind_4});
        
        Panel_Central.removeAll();
        Panel_Central.repaint();
        Panel_Central.revalidate();
        
        Panel_Central.add(Central1);
        Panel_Central.repaint();
        Panel_Central.revalidate();
        
    }//GEN-LAST:event_btn_InicioMousePressed

    private void btn_ConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultasMousePressed
        // TODO add your handling code here:
         setColor(btn_Consultas); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_Registros,btn_Inicio,btn_Modificar}, new JPanel[]{ind_2,ind_1, ind_4});
        Panel_Central.removeAll();
        Panel_Central.repaint();
        Panel_Central.revalidate();
        
        Panel_Central.add(Central2);
        Panel_Central.repaint();
        Panel_Central.revalidate();
    }//GEN-LAST:event_btn_ConsultasMousePressed

    private void btn_ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModificarMousePressed
        // TODO add your handling code here:
          setColor(btn_Modificar); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_Registros,btn_Consultas,btn_Inicio}, new JPanel[]{ind_2,ind_3, ind_1});
        Panel_Central.removeAll();
        Panel_Central.repaint();
        Panel_Central.revalidate();
        
        Panel_Central.add(Central3);
        Panel_Central.repaint();
        Panel_Central.revalidate();
    }//GEN-LAST:event_btn_ModificarMousePressed

    private void btn_RegistrosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistrosMouseReleased
        // TODO add your handling code here:
          setColor(btn_Registros); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Consultas,btn_Modificar}, new JPanel[]{ind_1,ind_3, ind_4});
        Panel_Central.removeAll();
        Panel_Central.repaint();
        Panel_Central.revalidate();
        
        Panel_Central.add(Central4);
        Panel_Central.repaint();
        Panel_Central.revalidate();
    }//GEN-LAST:event_btn_RegistrosMouseReleased

    int xx,xy;
    private void Barra_SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Barra_SuperiorMousePressed

    private void Barra_SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_Barra_SuperiorMouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JPanel Barra_Superior;
    private javax.swing.JButton BorrarUsuario;
    private javax.swing.JPanel Central1;
    private javax.swing.JPanel Central2;
    private javax.swing.JPanel Central3;
    private javax.swing.JPanel Central4;
    private javax.swing.JButton ConfigUsuario;
    private javax.swing.JPanel Panel_Central;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel btn_Consultas;
    private javax.swing.JPanel btn_Inicio;
    private javax.swing.JPanel btn_Modificar;
    private javax.swing.JPanel btn_Registros;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
