/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.event.KeyEvent;


/**
 *
 * @author esteban
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        menuPass = new javax.swing.JTextField();
        menuNomb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menuIniciar = new javax.swing.JButton();
        menuCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaptionBorder);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(16, 129, 129));
        jPanel2.setLayout(null);

        jPasswordField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(130, 300, 290, 50);

        menuPass.setBorder(null);
        menuPass.setOpaque(false);
        jPanel2.add(menuPass);
        menuPass.setBounds(130, 300, 290, 50);

        menuNomb.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        menuNomb.setBorder(null);
        menuNomb.setOpaque(false);
        menuNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuNombKeyPressed(evt);
            }
        });
        jPanel2.add(menuNomb);
        menuNomb.setBounds(130, 230, 290, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/txt_user.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 220, 340, 70);

        menuIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_iniciar_2.png"))); // NOI18N
        menuIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_iniciar_1.png"))); // NOI18N
        menuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarActionPerformed(evt);
            }
        });
        jPanel2.add(menuIniciar);
        menuIniciar.setBounds(140, 370, 100, 50);

        menuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_2.png"))); // NOI18N
        menuCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_2.png"))); // NOI18N
        menuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(menuCancelar);
        menuCancelar.setBounds(270, 370, 100, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/txt_pass.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 290, 340, 70);

        jLabel3.setBackground(new java.awt.Color(247, 243, 247));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 224, 236));
        jLabel3.setText("Inicio de sesion");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 180, 210, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 10, 200, 170);

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        jPanel2.add(btn_exit);
        btn_exit.setBounds(470, 0, 30, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarActionPerformed
        String nombre = menuNomb.getText();
        if("macaco".equals(nombre)){ //Usuario correcto
            MenuInicio menuinicio = new MenuInicio();
            menuinicio.setVisible(true);
            this.setVisible(false);
        }
        else{ //Usuario incorrecto
            VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
            error.setVisible(true);
        }
    }//GEN-LAST:event_menuIniciarActionPerformed

    private void menuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelarActionPerformed
      System.exit(0);
    }//GEN-LAST:event_menuCancelarActionPerformed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void menuNombKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuNombKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String nombre = menuNomb.getText();
            if("macaco".equals(nombre)){ //Usuario correcto
                MenuInicio menuinicio = new MenuInicio();
                menuinicio.setVisible(true);
                this.setVisible(false);
            }
            else{ //Usuario incorrecto
                VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_menuNombKeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String nombre = menuNomb.getText();
            if("macaco".equals(nombre)){ //Usuario correcto
                MenuInicio menuinicio = new MenuInicio();
                menuinicio.setVisible(true);
                this.setVisible(false);
            }
            else{ //Usuario incorrecto
                VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton menuCancelar;
    private javax.swing.JButton menuIniciar;
    private javax.swing.JTextField menuNomb;
    private javax.swing.JTextField menuPass;
    // End of variables declaration//GEN-END:variables
}
