/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;


/**
 *
 * @author esteban
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    Font fn = null;
    public Menu() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoAPP.png")));
        setLocationRelativeTo(null);      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        menuNomb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menuIniciar = new javax.swing.JButton();
        menuCancelar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DragPanel = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaptionBorder);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(16, 129, 129));
        jPanel2.setLayout(null);

        jPasswordField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(130, 300, 290, 50);

        menuNomb.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        menuNomb.setBorder(null);
        menuNomb.setOpaque(false);
        menuNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuNombKeyPressed(evt);
            }
        });
        jPanel2.add(menuNomb);
        menuNomb.setBounds(130, 230, 290, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/txt_user.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 220, 340, 70);

        menuIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_iniciar_2.png"))); // NOI18N
        menuIniciar.setBorderPainted(false);
        menuIniciar.setContentAreaFilled(false);
        menuIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_iniciar_1.png"))); // NOI18N
        menuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarActionPerformed(evt);
            }
        });
        jPanel2.add(menuIniciar);
        menuIniciar.setBounds(140, 370, 100, 50);

        menuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_2.png"))); // NOI18N
        menuCancelar.setBorderPainted(false);
        menuCancelar.setContentAreaFilled(false);
        menuCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_1.png"))); // NOI18N
        menuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(menuCancelar);
        menuCancelar.setBounds(270, 370, 100, 50);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar2.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(cerrar);
        cerrar.setBounds(470, 10, 20, 20);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar2.png"))); // NOI18N
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        jPanel2.add(minimizar);
        minimizar.setBounds(440, 10, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/txt_pass.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 290, 340, 70);

        jLabel3.setBackground(new java.awt.Color(247, 243, 247));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 224, 236));
        jLabel3.setText("Inicio de sesión");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 180, 220, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 10, 200, 170);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 510);

        DragPanel.setBackground(new java.awt.Color(12, 129, 129));
        DragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragPanelMouseDragged(evt);
            }
        });
        DragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DragPanelLayout = new javax.swing.GroupLayout(DragPanel);
        DragPanel.setLayout(DragPanelLayout);
        DragPanelLayout.setHorizontalGroup(
            DragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DragPanelLayout.setVerticalGroup(
            DragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(DragPanel);
        DragPanel.setBounds(0, 0, 500, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarActionPerformed
        String nombre = menuNomb.getText();
        if("macaco".equals(nombre)){ //Usuario correcto
            MenuInicio menuinicio = new MenuInicio();
            menuinicio.setVisible(true);
            this.setVisible(false);
        }
        else{ //Usuario incorrecto
            VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
            
            error.CambioTexto("Los datos ingresados son incorrectos");
            error.setVisible(true);
           
        }
    }//GEN-LAST:event_menuIniciarActionPerformed

    private void menuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelarActionPerformed
      System.exit(0);
    }//GEN-LAST:event_menuCancelarActionPerformed

    private void menuNombKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuNombKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String nombre = menuNomb.getText();
            if("macaco".equals(nombre)){ //Usuario correcto
                MenuInicio menuinicio = new MenuInicio();
                menuinicio.setVisible(true);
                menuinicio.SetAdmin(nombre);
                this.setVisible(false);
            }
            else{ //Usuario incorrecto
                VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
                error.CambioTexto("Los datos ingresados son incorrectos");
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_menuNombKeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String nombre = menuNomb.getText();
            if("macaco".equals(nombre)){ //Usuario correcto
                MenuInicio menuinicio = new MenuInicio();
                menuinicio.setVisible(true);
                menuinicio.SetAdmin(nombre);
                this.setVisible(false);
            }
            else{ //Usuario incorrecto
                VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
                error.CambioTexto("Los datos ingresados son incorrectos");
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
      System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        setState(Menu.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed
int xx,xy;
    private void DragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_DragPanelMouseDragged

    private void DragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_DragPanelMousePressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DragPanel;
    private javax.swing.JButton cerrar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton menuCancelar;
    private javax.swing.JButton menuIniciar;
    private javax.swing.JTextField menuNomb;
    private javax.swing.JButton minimizar;
    // End of variables declaration//GEN-END:variables
}
