/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public MenuInicio() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoAPP.png")));
        setLocationRelativeTo(null);
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Usuario,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Lateral = new javax.swing.JPanel();
        btn_Inicio = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_Usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        btn_Consultas = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_Modificar = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_CerrarSesion = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Barra_Superior = new javax.swing.JPanel();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        Panel_Central = new javax.swing.JPanel();
        Central1 = new javax.swing.JPanel();
        Central2 = new javax.swing.JPanel();
        AgregarUsuario = new javax.swing.JButton();
        BorrarUsuario = new javax.swing.JButton();
        ConfigUsuario = new javax.swing.JButton();
        Central3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Central4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Central2_1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nickname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        FechNac = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        AgregarFoto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        Registrar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NombCanal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(23, 35, 51));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Inicio.setBackground(new java.awt.Color(23, 35, 51));
        btn_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InicioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");

        javax.swing.GroupLayout btn_InicioLayout = new javax.swing.GroupLayout(btn_Inicio);
        btn_Inicio.setLayout(btn_InicioLayout);
        btn_InicioLayout.setHorizontalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        btn_InicioLayout.setVerticalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, -1));

        btn_Usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_UsuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");

        javax.swing.GroupLayout btn_UsuarioLayout = new javax.swing.GroupLayout(btn_Usuario);
        btn_Usuario.setLayout(btn_UsuarioLayout);
        btn_UsuarioLayout.setHorizontalGroup(
            btn_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Usuario)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        btn_UsuarioLayout.setVerticalGroup(
            btn_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, -1));

        btn_Consultas.setBackground(new java.awt.Color(23, 35, 51));
        btn_Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ConsultasMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Consultas");

        javax.swing.GroupLayout btn_ConsultasLayout = new javax.swing.GroupLayout(btn_Consultas);
        btn_Consultas.setLayout(btn_ConsultasLayout);
        btn_ConsultasLayout.setHorizontalGroup(
            btn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        btn_ConsultasLayout.setVerticalGroup(
            btn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, -1));

        btn_Modificar.setBackground(new java.awt.Color(23, 35, 51));
        btn_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ModificarMousePressed(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modificar");

        javax.swing.GroupLayout btn_ModificarLayout = new javax.swing.GroupLayout(btn_Modificar);
        btn_Modificar.setLayout(btn_ModificarLayout);
        btn_ModificarLayout.setHorizontalGroup(
            btn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        btn_ModificarLayout.setVerticalGroup(
            btn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, -1));

        btn_CerrarSesion.setBackground(new java.awt.Color(23, 35, 51));
        btn_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CerrarSesionMousePressed(evt);
            }
        });

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cerrar Sesion");

        javax.swing.GroupLayout btn_CerrarSesionLayout = new javax.swing.GroupLayout(btn_CerrarSesion);
        btn_CerrarSesion.setLayout(btn_CerrarSesionLayout);
        btn_CerrarSesionLayout.setHorizontalGroup(
            btn_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        btn_CerrarSesionLayout.setVerticalGroup(
            btn_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, -1));

        getContentPane().add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 590));

        Barra_Superior.setBackground(new java.awt.Color(12, 129, 129));
        Barra_Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMouseDragged(evt);
            }
        });
        Barra_Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMousePressed(evt);
            }
        });
        Barra_Superior.setLayout(null);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar2.png"))); // NOI18N
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        Barra_Superior.add(minimizar);
        minimizar.setBounds(660, 10, 20, 20);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar2.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        Barra_Superior.add(cerrar);
        cerrar.setBounds(690, 10, 20, 20);

        getContentPane().add(Barra_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 40));

        Panel_Central.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Central1Layout = new javax.swing.GroupLayout(Central1);
        Central1.setLayout(Central1Layout);
        Central1Layout.setHorizontalGroup(
            Central1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        Central1Layout.setVerticalGroup(
            Central1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        AgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddUser 1.png"))); // NOI18N
        AgregarUsuario.setBorderPainted(false);
        AgregarUsuario.setContentAreaFilled(false);
        AgregarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddUser 2.png"))); // NOI18N
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });

        BorrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BorrarUser1.png"))); // NOI18N
        BorrarUsuario.setBorderPainted(false);
        BorrarUsuario.setContentAreaFilled(false);
        BorrarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BorrarUser 2.png"))); // NOI18N

        ConfigUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config 1.png"))); // NOI18N
        ConfigUsuario.setBorderPainted(false);
        ConfigUsuario.setContentAreaFilled(false);
        ConfigUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config 2.png"))); // NOI18N

        javax.swing.GroupLayout Central2Layout = new javax.swing.GroupLayout(Central2);
        Central2.setLayout(Central2Layout);
        Central2Layout.setHorizontalGroup(
            Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarUsuario)
                    .addComponent(ConfigUsuario))
                .addGap(46, 46, 46)
                .addComponent(BorrarUsuario)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Central2Layout.setVerticalGroup(
            Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Central2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarUsuario)
                    .addGroup(Central2Layout.createSequentialGroup()
                        .addComponent(AgregarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfigUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AgregarUsuario.getAccessibleContext().setAccessibleName("AgregarUsuario");
        BorrarUsuario.getAccessibleContext().setAccessibleName("BorrarUsuario");
        ConfigUsuario.getAccessibleContext().setAccessibleName("ConfigUsuario");

        jLabel3.setText("PANEL CONSULTAS");

        javax.swing.GroupLayout Central3Layout = new javax.swing.GroupLayout(Central3);
        Central3.setLayout(Central3Layout);
        Central3Layout.setHorizontalGroup(
            Central3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        Central3Layout.setVerticalGroup(
            Central3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central3Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jLabel4.setText("PANEL MODIFICAR");

        javax.swing.GroupLayout Central4Layout = new javax.swing.GroupLayout(Central4);
        Central4.setLayout(Central4Layout);
        Central4Layout.setHorizontalGroup(
            Central4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Central4Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        Central4Layout.setVerticalGroup(
            Central4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central4Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        Central2_1.setMinimumSize(new java.awt.Dimension(720, 560));
        Central2_1.setLayout(null);

        Nombre.setText("Nombre (*)");
        Central2_1.add(Nombre);
        Nombre.setBounds(160, 100, 120, 18);

        Apellido.setText("Apellido (*)");
        Central2_1.add(Apellido);
        Apellido.setBounds(160, 140, 100, 18);

        Nickname.setText("Nickname (*)");
        Central2_1.add(Nickname);
        Nickname.setBounds(160, 60, 120, 18);

        jLabel6.setText("Correo (*)");
        Central2_1.add(jLabel6);
        jLabel6.setBounds(160, 220, 110, 18);
        Central2_1.add(txtNick);
        txtNick.setBounds(330, 50, 151, 28);
        Central2_1.add(txtNombre);
        txtNombre.setBounds(330, 90, 151, 28);
        Central2_1.add(txtApellido);
        txtApellido.setBounds(330, 130, 151, 28);
        Central2_1.add(txtDia);
        txtDia.setBounds(330, 180, 54, 28);

        FechNac.setText("Fecha de nacimiento (*)");
        Central2_1.add(FechNac);
        FechNac.setBounds(160, 190, 220, 18);
        Central2_1.add(txtMes);
        txtMes.setBounds(390, 180, 54, 28);
        Central2_1.add(txtCorreo);
        txtCorreo.setBounds(330, 220, 259, 28);
        Central2_1.add(txtAnio);
        txtAnio.setBounds(450, 180, 54, 28);

        AgregarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_norm.png"))); // NOI18N
        Central2_1.add(AgregarFoto);
        AgregarFoto.setBounds(180, 390, 30, 30);

        jLabel12.setText("Subir imagen .jpg o .png");
        Central2_1.add(jLabel12);
        jLabel12.setBounds(230, 400, 270, 18);

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_2.png"))); // NOI18N
        Cancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_1.png"))); // NOI18N
        Central2_1.add(Cancelar);
        Cancelar.setBounds(400, 480, 100, 47);

        Registrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_regist_2.png"))); // NOI18N
        Registrar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_regist_1.png"))); // NOI18N
        Central2_1.add(Registrar1);
        Registrar1.setBounds(230, 480, 100, 47);

        jLabel2.setText("Nombre del canal");
        Central2_1.add(jLabel2);
        jLabel2.setBounds(160, 260, 130, 18);
        Central2_1.add(NombCanal);
        NombCanal.setBounds(330, 260, 260, 28);

        jLabel5.setText("Descripcion del canal (*)");
        Central2_1.add(jLabel5);
        jLabel5.setBounds(160, 300, 190, 18);
        Central2_1.add(jTextField1);
        jTextField1.setBounds(330, 300, 260, 70);

        javax.swing.GroupLayout Panel_CentralLayout = new javax.swing.GroupLayout(Panel_Central);
        Panel_Central.setLayout(Panel_CentralLayout);
        Panel_CentralLayout.setHorizontalGroup(
            Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Central1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        Panel_CentralLayout.setVerticalGroup(
            Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Central1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Central2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 720, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InicioMousePressed
        // TODO add your handling code here:
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Usuario,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        
    }//GEN-LAST:event_btn_InicioMousePressed

    private void btn_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UsuarioMousePressed
        // TODO add your handling code here:
         setColor(btn_Usuario); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Inicio,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_2,ind_1,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_UsuarioMousePressed

    private void btn_ConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultasMousePressed
        // TODO add your handling code here:
          setColor(btn_Consultas); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Usuario,btn_Inicio,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_1,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central3);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_ConsultasMousePressed

    int xx,xy;
    private void Barra_SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Barra_SuperiorMousePressed

    private void Barra_SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_Barra_SuperiorMouseDragged

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        setState(Menu.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void btn_CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarSesionMousePressed
        btn_CerrarSesion.setBackground(new Color(235,76,76));
        ind_5.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Usuario,btn_Consultas,btn_Modificar}, new JPanel[]{ind_1,ind_3,ind_4,ind_2});
        VentanaEmergente2 error = new VentanaEmergente2(this, rootPaneCheckingEnabled,this);
        error.setVisible(true);
    }//GEN-LAST:event_btn_CerrarSesionMousePressed

    private void btn_ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModificarMousePressed
        setColor(btn_Modificar); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Usuario,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_1,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central4);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_ModificarMousePressed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2_1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
   
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23,35,51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    
    public MenuInicio getFrame(){
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarFoto;
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JLabel Apellido;
    private javax.swing.JPanel Barra_Superior;
    private javax.swing.JButton BorrarUsuario;
    private javax.swing.JButton Cancelar;
    private javax.swing.JPanel Central1;
    private javax.swing.JPanel Central2;
    private javax.swing.JPanel Central2_1;
    private javax.swing.JPanel Central3;
    private javax.swing.JPanel Central4;
    private javax.swing.JButton ConfigUsuario;
    private javax.swing.JLabel FechNac;
    private javax.swing.JLabel Nickname;
    private javax.swing.JTextField NombCanal;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Panel_Central;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JButton Registrar1;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel btn_CerrarSesion;
    private javax.swing.JPanel btn_Consultas;
    private javax.swing.JPanel btn_Inicio;
    private javax.swing.JPanel btn_Modificar;
    private javax.swing.JPanel btn_Usuario;
    private javax.swing.JButton cerrar;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton minimizar;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
