/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;


import DataTypes.DtCanal;
import DataTypes.DtUsuario;
import clases.Usuario;
import excepciones.UsuarioRepetidoException;
import fabrica.Fabrica;
import interfaces.IControladorUsuario;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String Item;
    Fabrica fabrica = Fabrica.getInstance();
    IControladorUsuario u = fabrica.getControladorUsuario();
    
    private String rutaImagen;
    private BufferedImage imagen;
    
    public MenuInicio() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoAPP.png")));
        setLocationRelativeTo(null);
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Playlist,btn_Usuario,btn_Video,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Lateral = new javax.swing.JPanel();
        btn_Categorias = new javax.swing.JPanel();
        ind_6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_Inicio = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_Usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        UsuarioBarra = new javax.swing.JLabel();
        btn_Video = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_Playlist = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_CerrarSesion = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Barra_Superior = new javax.swing.JPanel();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        AdministradorText = new javax.swing.JLabel();
        AdminChange = new javax.swing.JLabel();
        Panel_Central = new javax.swing.JPanel();
        Central1 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        Central2 = new javax.swing.JPanel();
        ConsultarUsuariosText = new javax.swing.JLabel();
        ListarUsuariosText = new javax.swing.JLabel();
        ModificarUsuarioText = new javax.swing.JLabel();
        AgregarUserText = new javax.swing.JLabel();
        AgregarUsuario = new javax.swing.JButton();
        ModificarUsuario = new javax.swing.JButton();
        ListarUsuarios = new javax.swing.JButton();
        ConsultarUsuarios = new javax.swing.JButton();
        Central3 = new javax.swing.JPanel();
        consultaVid = new javax.swing.JLabel();
        agregarVid = new javax.swing.JLabel();
        modificarVid = new javax.swing.JLabel();
        modVid_Button = new javax.swing.JButton();
        agrVid_Button = new javax.swing.JButton();
        consVid_Button = new javax.swing.JButton();
        agregarVid3 = new javax.swing.JLabel();
        Scroll4 = new javax.swing.JScrollPane();
        Central4 = new javax.swing.JPanel();
        quitarVideo = new javax.swing.JLabel();
        crearPlaylist = new javax.swing.JLabel();
        modificarPlaylist = new javax.swing.JLabel();
        consultaPlaylist = new javax.swing.JLabel();
        agregarVideo = new javax.swing.JLabel();
        crearPlaylist_Button = new javax.swing.JButton();
        modificarPlaylist_Button = new javax.swing.JButton();
        quitarVideo_Button = new javax.swing.JButton();
        consultaPlaylist_button = new javax.swing.JButton();
        agregarVideo_Button = new javax.swing.JButton();
        Central5 = new javax.swing.JPanel();
        consultaCat = new javax.swing.JLabel();
        listarCat = new javax.swing.JLabel();
        agregarCat = new javax.swing.JLabel();
        consultaCat_Button = new javax.swing.JButton();
        listarCat_Button = new javax.swing.JButton();
        agregarCat_Button = new javax.swing.JButton();
        Central2_1 = new javax.swing.JPanel();
        Canal = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Nickname = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        FechaNac = new javax.swing.JLabel();
        Privado = new javax.swing.JLabel();
        NombreCanal = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        AgregarImg = new javax.swing.JLabel();
        CampoNickname = new javax.swing.JTextField();
        CampoContraseña = new javax.swing.JPasswordField();
        CampoNombre = new javax.swing.JTextField();
        CampoApellido = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        CampoCanal = new javax.swing.JTextField();
        CampoImagen = new javax.swing.JTextField();
        DateChoose = new com.toedter.calendar.JDateChooser();
        AgregarFoto = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CheckboxPrivado = new java.awt.Checkbox();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        ScroolDescripcion = new javax.swing.JScrollPane();
        CampoDescripcion = new javax.swing.JTextArea();
        Central2_2 = new javax.swing.JPanel();
        comboConsulta = new javax.swing.JComboBox<>();
        BackButton3 = new javax.swing.JButton();
        SeleccionarUsuario = new javax.swing.JButton();
        Central2_2_Panel = new javax.swing.JPanel();
        jSeparator18 = new javax.swing.JSeparator();
        Central2_4 = new javax.swing.JPanel();
        comboLista = new javax.swing.JComboBox<>();
        BackButton2 = new javax.swing.JButton();
        Central2_2_1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        nick = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Varnick = new javax.swing.JTextField();
        mail = new javax.swing.JLabel();
        Varnom = new javax.swing.JTextField();
        Varape = new javax.swing.JTextField();
        Varfech = new javax.swing.JTextField();
        Varmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        Imagen = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(73, 73, 73));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Categorias.setBackground(new java.awt.Color(73, 73, 73));
        btn_Categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CategoriasMousePressed(evt);
            }
        });

        ind_6.setOpaque(false);
        ind_6.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_6Layout = new javax.swing.GroupLayout(ind_6);
        ind_6.setLayout(ind_6Layout);
        ind_6Layout.setHorizontalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_6Layout.setVerticalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Categorías");

        javax.swing.GroupLayout btn_CategoriasLayout = new javax.swing.GroupLayout(btn_Categorias);
        btn_Categorias.setLayout(btn_CategoriasLayout);
        btn_CategoriasLayout.setHorizontalGroup(
            btn_CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CategoriasLayout.createSequentialGroup()
                .addComponent(ind_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        btn_CategoriasLayout.setVerticalGroup(
            btn_CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CategoriasLayout.createSequentialGroup()
                .addComponent(ind_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_CategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, -1));

        btn_Inicio.setBackground(new java.awt.Color(73, 73, 73));
        btn_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InicioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");

        javax.swing.GroupLayout btn_InicioLayout = new javax.swing.GroupLayout(btn_Inicio);
        btn_Inicio.setLayout(btn_InicioLayout);
        btn_InicioLayout.setHorizontalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        btn_InicioLayout.setVerticalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, -1));

        btn_Usuario.setBackground(new java.awt.Color(73, 73, 73));
        btn_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_UsuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        UsuarioBarra.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        UsuarioBarra.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioBarra.setText("Usuario");

        javax.swing.GroupLayout btn_UsuarioLayout = new javax.swing.GroupLayout(btn_Usuario);
        btn_Usuario.setLayout(btn_UsuarioLayout);
        btn_UsuarioLayout.setHorizontalGroup(
            btn_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(UsuarioBarra)
                .addGap(0, 73, Short.MAX_VALUE))
        );
        btn_UsuarioLayout.setVerticalGroup(
            btn_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsuarioBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, -1));

        btn_Video.setBackground(new java.awt.Color(73, 73, 73));
        btn_Video.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_VideoMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Video");

        javax.swing.GroupLayout btn_VideoLayout = new javax.swing.GroupLayout(btn_Video);
        btn_Video.setLayout(btn_VideoLayout);
        btn_VideoLayout.setHorizontalGroup(
            btn_VideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_VideoLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 86, Short.MAX_VALUE))
        );
        btn_VideoLayout.setVerticalGroup(
            btn_VideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_VideoLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_VideoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Video, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, -1));

        btn_Playlist.setBackground(new java.awt.Color(73, 73, 73));
        btn_Playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PlaylistMousePressed(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Playlists");

        javax.swing.GroupLayout btn_PlaylistLayout = new javax.swing.GroupLayout(btn_Playlist);
        btn_Playlist.setLayout(btn_PlaylistLayout);
        btn_PlaylistLayout.setHorizontalGroup(
            btn_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_PlaylistLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 69, Short.MAX_VALUE))
        );
        btn_PlaylistLayout.setVerticalGroup(
            btn_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_PlaylistLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_PlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Playlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, -1));

        btn_CerrarSesion.setBackground(new java.awt.Color(73, 73, 73));
        btn_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CerrarSesionMousePressed(evt);
            }
        });

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cerrar Sesión");

        javax.swing.GroupLayout btn_CerrarSesionLayout = new javax.swing.GroupLayout(btn_CerrarSesion);
        btn_CerrarSesion.setLayout(btn_CerrarSesionLayout);
        btn_CerrarSesionLayout.setHorizontalGroup(
            btn_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        btn_CerrarSesionLayout.setVerticalGroup(
            btn_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, -1));

        getContentPane().add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 590));

        Barra_Superior.setBackground(new java.awt.Color(12, 129, 129));
        Barra_Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMouseDragged(evt);
            }
        });
        Barra_Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMousePressed(evt);
            }
        });
        Barra_Superior.setLayout(null);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar2.png"))); // NOI18N
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        Barra_Superior.add(minimizar);
        minimizar.setBounds(660, 10, 20, 20);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar2.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        Barra_Superior.add(cerrar);
        cerrar.setBounds(690, 10, 20, 20);

        AdministradorText.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        AdministradorText.setForeground(new java.awt.Color(255, 255, 255));
        AdministradorText.setText("Administrador: ");
        Barra_Superior.add(AdministradorText);
        AdministradorText.setBounds(20, 10, 130, 20);

        AdminChange.setFont(new java.awt.Font("Manjari Bold", 1, 14)); // NOI18N
        AdminChange.setForeground(new java.awt.Color(255, 255, 255));
        Barra_Superior.add(AdminChange);
        AdminChange.setBounds(120, 10, 140, 20);

        getContentPane().add(Barra_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 40));

        Panel_Central.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Central.setLayout(null);

        Central1.setLayout(null);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoHome.gif"))); // NOI18N
        Central1.add(fondo);
        fondo.setBounds(0, 0, 720, 550);

        Panel_Central.add(Central1);
        Central1.setBounds(0, 0, 720, 550);

        Central2.setForeground(new java.awt.Color(255, 255, 255));
        Central2.setLayout(null);

        ConsultarUsuariosText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConsultarUsuariosText.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarUsuariosText.setText("Consultar Usuario");
        Central2.add(ConsultarUsuariosText);
        ConsultarUsuariosText.setBounds(450, 50, 130, 20);

        ListarUsuariosText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListarUsuariosText.setForeground(new java.awt.Color(255, 255, 255));
        ListarUsuariosText.setText("Listar Usuarios");
        Central2.add(ListarUsuariosText);
        ListarUsuariosText.setBounds(460, 300, 120, 20);

        ModificarUsuarioText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModificarUsuarioText.setForeground(new java.awt.Color(255, 255, 255));
        ModificarUsuarioText.setText("Modificar Usuario");
        Central2.add(ModificarUsuarioText);
        ModificarUsuarioText.setBounds(150, 300, 130, 20);

        AgregarUserText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AgregarUserText.setForeground(new java.awt.Color(255, 255, 255));
        AgregarUserText.setText("Agregar Usuario");
        Central2.add(AgregarUserText);
        AgregarUserText.setBounds(160, 50, 120, 20);

        AgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarUser.png"))); // NOI18N
        AgregarUsuario.setBorderPainted(false);
        AgregarUsuario.setContentAreaFilled(false);
        AgregarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarUser2.png"))); // NOI18N
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });
        Central2.add(AgregarUsuario);
        AgregarUsuario.setBounds(90, 40, 243, 221);
        AgregarUsuario.getAccessibleContext().setAccessibleName("AgregarUsuario");

        ModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarUser.png"))); // NOI18N
        ModificarUsuario.setBorderPainted(false);
        ModificarUsuario.setContentAreaFilled(false);
        ModificarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarUser2.png"))); // NOI18N
        ModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioActionPerformed(evt);
            }
        });
        Central2.add(ModificarUsuario);
        ModificarUsuario.setBounds(90, 290, 243, 221);

        ListarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Listar.png"))); // NOI18N
        ListarUsuarios.setBorderPainted(false);
        ListarUsuarios.setContentAreaFilled(false);
        ListarUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Listar2.png"))); // NOI18N
        ListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuariosActionPerformed(evt);
            }
        });
        Central2.add(ListarUsuarios);
        ListarUsuarios.setBounds(390, 290, 243, 221);

        ConsultarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarUser.png"))); // NOI18N
        ConsultarUsuarios.setBorderPainted(false);
        ConsultarUsuarios.setContentAreaFilled(false);
        ConsultarUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarUser2.png"))); // NOI18N
        ConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarUsuariosActionPerformed(evt);
            }
        });
        Central2.add(ConsultarUsuarios);
        ConsultarUsuarios.setBounds(390, 40, 243, 221);

        Panel_Central.add(Central2);
        Central2.setBounds(0, 0, 720, 550);

        Central3.setLayout(null);

        consultaVid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaVid.setForeground(new java.awt.Color(255, 255, 255));
        consultaVid.setText("Consulta video");
        Central3.add(consultaVid);
        consultaVid.setBounds(160, 300, 130, 20);

        agregarVid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarVid.setForeground(new java.awt.Color(255, 255, 255));
        agregarVid.setText("Agregar video");
        Central3.add(agregarVid);
        agregarVid.setBounds(170, 50, 130, 20);

        modificarVid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarVid.setForeground(new java.awt.Color(255, 255, 255));
        modificarVid.setText("Modificar video");
        Central3.add(modificarVid);
        modificarVid.setBounds(470, 50, 130, 20);

        modVid_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarVideo.png"))); // NOI18N
        modVid_Button.setBorderPainted(false);
        modVid_Button.setContentAreaFilled(false);
        modVid_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarVideo2.png"))); // NOI18N
        modVid_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modVid_ButtonActionPerformed(evt);
            }
        });
        Central3.add(modVid_Button);
        modVid_Button.setBounds(390, 40, 240, 220);

        agrVid_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarVideo.png"))); // NOI18N
        agrVid_Button.setBorderPainted(false);
        agrVid_Button.setContentAreaFilled(false);
        agrVid_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarVideo2.png"))); // NOI18N
        agrVid_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrVid_ButtonActionPerformed(evt);
            }
        });
        Central3.add(agrVid_Button);
        agrVid_Button.setBounds(100, 40, 230, 220);

        consVid_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarVideo.png"))); // NOI18N
        consVid_Button.setBorderPainted(false);
        consVid_Button.setContentAreaFilled(false);
        consVid_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarVideo2.png"))); // NOI18N
        consVid_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consVid_ButtonActionPerformed(evt);
            }
        });
        Central3.add(consVid_Button);
        consVid_Button.setBounds(100, 290, 230, 220);

        agregarVid3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarVid3.setForeground(new java.awt.Color(255, 255, 255));
        agregarVid3.setText("Agregar video");
        Central3.add(agregarVid3);
        agregarVid3.setBounds(130, 50, 130, 20);

        Panel_Central.add(Central3);
        Central3.setBounds(0, 0, 720, 550);

        Scroll4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Scroll4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Central4.setPreferredSize(new java.awt.Dimension(720, 780));
        Central4.setLayout(null);

        quitarVideo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quitarVideo.setForeground(new java.awt.Color(255, 255, 255));
        quitarVideo.setText("Quitar video");
        Central4.add(quitarVideo);
        quitarVideo.setBounds(460, 300, 130, 20);

        crearPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crearPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        crearPlaylist.setText("Crear playlist");
        Central4.add(crearPlaylist);
        crearPlaylist.setBounds(170, 50, 130, 20);

        modificarPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        modificarPlaylist.setText("Modificar playlist");
        Central4.add(modificarPlaylist);
        modificarPlaylist.setBounds(450, 50, 130, 20);

        consultaPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        consultaPlaylist.setText("Consulta playlist");
        Central4.add(consultaPlaylist);
        consultaPlaylist.setBounds(160, 550, 130, 20);

        agregarVideo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarVideo.setForeground(new java.awt.Color(255, 255, 255));
        agregarVideo.setText("Agregar video");
        Central4.add(agregarVideo);
        agregarVideo.setBounds(170, 300, 130, 20);

        crearPlaylist_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarPlaylist.png"))); // NOI18N
        crearPlaylist_Button.setBorderPainted(false);
        crearPlaylist_Button.setContentAreaFilled(false);
        crearPlaylist_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarPlaylist2.png"))); // NOI18N
        Central4.add(crearPlaylist_Button);
        crearPlaylist_Button.setBounds(100, 40, 230, 210);

        modificarPlaylist_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarPlaylist.png"))); // NOI18N
        modificarPlaylist_Button.setBorderPainted(false);
        modificarPlaylist_Button.setContentAreaFilled(false);
        modificarPlaylist_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarPlaylist2.png"))); // NOI18N
        Central4.add(modificarPlaylist_Button);
        modificarPlaylist_Button.setBounds(390, 40, 230, 210);

        quitarVideo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BorrarVideoPlaylist.png"))); // NOI18N
        quitarVideo_Button.setBorderPainted(false);
        quitarVideo_Button.setContentAreaFilled(false);
        quitarVideo_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BorrarVideoPlaylist2.png"))); // NOI18N
        Central4.add(quitarVideo_Button);
        quitarVideo_Button.setBounds(390, 290, 230, 210);

        consultaPlaylist_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultaPlaylist.png"))); // NOI18N
        consultaPlaylist_button.setBorderPainted(false);
        consultaPlaylist_button.setContentAreaFilled(false);
        consultaPlaylist_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultaPlaylist2.png"))); // NOI18N
        consultaPlaylist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPlaylist_buttonActionPerformed(evt);
            }
        });
        Central4.add(consultaPlaylist_button);
        consultaPlaylist_button.setBounds(100, 540, 230, 210);

        agregarVideo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarVideoPlaylist.png"))); // NOI18N
        agregarVideo_Button.setBorderPainted(false);
        agregarVideo_Button.setContentAreaFilled(false);
        agregarVideo_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarVideoPlaylist2.png"))); // NOI18N
        Central4.add(agregarVideo_Button);
        agregarVideo_Button.setBounds(100, 290, 230, 210);

        Scroll4.setViewportView(Central4);

        Panel_Central.add(Scroll4);
        Scroll4.setBounds(0, 0, 720, 550);

        Central5.setLayout(null);

        consultaCat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaCat.setForeground(new java.awt.Color(255, 255, 255));
        consultaCat.setText("Consulta categoría");
        Central5.add(consultaCat);
        consultaCat.setBounds(440, 60, 130, 20);

        listarCat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listarCat.setForeground(new java.awt.Color(255, 255, 255));
        listarCat.setText("Listar categorías");
        Central5.add(listarCat);
        listarCat.setBounds(150, 310, 130, 20);

        agregarCat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarCat.setForeground(new java.awt.Color(255, 255, 255));
        agregarCat.setText("Agregar categoría");
        Central5.add(agregarCat);
        agregarCat.setBounds(150, 60, 130, 20);

        consultaCat_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultaCategoria.png"))); // NOI18N
        consultaCat_Button.setBorderPainted(false);
        consultaCat_Button.setContentAreaFilled(false);
        consultaCat_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultaCategoria2.png"))); // NOI18N
        Central5.add(consultaCat_Button);
        consultaCat_Button.setBounds(390, 50, 230, 210);

        listarCat_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ListarCategorias.png"))); // NOI18N
        listarCat_Button.setBorderPainted(false);
        listarCat_Button.setContentAreaFilled(false);
        listarCat_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ListarCategorias2.png"))); // NOI18N
        Central5.add(listarCat_Button);
        listarCat_Button.setBounds(100, 300, 230, 210);

        agregarCat_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarCategoria.png"))); // NOI18N
        agregarCat_Button.setBorderPainted(false);
        agregarCat_Button.setContentAreaFilled(false);
        agregarCat_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarCategoria2.png"))); // NOI18N
        Central5.add(agregarCat_Button);
        agregarCat_Button.setBounds(100, 50, 230, 210);

        Panel_Central.add(Central5);
        Central5.setBounds(0, 0, 720, 550);

        Central2_1.setMinimumSize(new java.awt.Dimension(720, 560));
        Central2_1.setLayout(null);

        Canal.setFont(new java.awt.Font("Manjari", 1, 18)); // NOI18N
        Canal.setText("Canal");
        Central2_1.add(Canal);
        Canal.setBounds(540, 40, 100, 20);

        Usuario.setFont(new java.awt.Font("Manjari", 1, 18)); // NOI18N
        Usuario.setText("Usuario");
        Central2_1.add(Usuario);
        Usuario.setBounds(170, 40, 100, 22);

        Nickname.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Nickname.setText("Nickname(*)");
        Central2_1.add(Nickname);
        Nickname.setBounds(40, 100, 100, 19);

        Contraseña.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Contraseña.setText("Contraseña(*)");
        Central2_1.add(Contraseña);
        Contraseña.setBounds(40, 140, 110, 19);

        Nombre.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Nombre.setText("Nombre(*)");
        Central2_1.add(Nombre);
        Nombre.setBounds(40, 180, 90, 19);

        Apellido.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Apellido.setText("Apellido(*)");
        Central2_1.add(Apellido);
        Apellido.setBounds(40, 220, 90, 19);

        Correo.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Correo.setText("Correo(*)");
        Central2_1.add(Correo);
        Correo.setBounds(40, 260, 90, 19);

        FechaNac.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        FechaNac.setText("Fecha de nacimiento(*)");
        Central2_1.add(FechaNac);
        FechaNac.setBounds(40, 370, 180, 20);

        Privado.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Privado.setText("¿Desea hacer el canal privado?");
        Central2_1.add(Privado);
        Privado.setBounds(450, 180, 230, 20);

        NombreCanal.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        NombreCanal.setText("Nombre del canal(opcional)");
        Central2_1.add(NombreCanal);
        NombreCanal.setBounds(450, 100, 220, 30);

        Descripcion.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        Descripcion.setText("Descripcion de canal(*)");
        Central2_1.add(Descripcion);
        Descripcion.setBounds(450, 220, 180, 40);

        AgregarImg.setFont(new java.awt.Font("Manjari Bold", 1, 16)); // NOI18N
        AgregarImg.setText("Agregar imágen(opcional)");
        Central2_1.add(AgregarImg);
        AgregarImg.setBounds(150, 420, 190, 40);

        CampoNickname.setBackground(new java.awt.Color(153, 153, 153));
        CampoNickname.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoNickname.setForeground(new java.awt.Color(102, 102, 102));
        CampoNickname.setText("Ingrese Nickname");
        CampoNickname.setBorder(null);
        CampoNickname.setNextFocusableComponent(CampoContraseña);
        CampoNickname.setOpaque(false);
        CampoNickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNicknameFocusGained(evt);
            }
        });
        Central2_1.add(CampoNickname);
        CampoNickname.setBounds(160, 100, 220, 20);

        CampoContraseña.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        CampoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        CampoContraseña.setText("*********");
        CampoContraseña.setBorder(null);
        CampoContraseña.setNextFocusableComponent(CampoNombre);
        CampoContraseña.setOpaque(false);
        CampoContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoContraseñaFocusGained(evt);
            }
        });
        Central2_1.add(CampoContraseña);
        CampoContraseña.setBounds(160, 140, 220, 16);

        CampoNombre.setBackground(new java.awt.Color(153, 153, 153));
        CampoNombre.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoNombre.setForeground(new java.awt.Color(102, 102, 102));
        CampoNombre.setText("Ingrese Nombre");
        CampoNombre.setBorder(null);
        CampoNombre.setNextFocusableComponent(CampoApellido);
        CampoNombre.setOpaque(false);
        CampoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNombreFocusGained(evt);
            }
        });
        Central2_1.add(CampoNombre);
        CampoNombre.setBounds(160, 180, 220, 20);

        CampoApellido.setBackground(new java.awt.Color(153, 153, 153));
        CampoApellido.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoApellido.setForeground(new java.awt.Color(102, 102, 102));
        CampoApellido.setText("Ingrese Apellido");
        CampoApellido.setBorder(null);
        CampoApellido.setNextFocusableComponent(CampoCorreo);
        CampoApellido.setOpaque(false);
        CampoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoApellidoFocusGained(evt);
            }
        });
        Central2_1.add(CampoApellido);
        CampoApellido.setBounds(160, 220, 220, 20);

        CampoCorreo.setBackground(new java.awt.Color(153, 153, 153));
        CampoCorreo.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoCorreo.setForeground(new java.awt.Color(102, 102, 102));
        CampoCorreo.setText("Ingrese Correo");
        CampoCorreo.setBorder(null);
        CampoCorreo.setNextFocusableComponent(CampoCanal);
        CampoCorreo.setOpaque(false);
        CampoCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoCorreoFocusGained(evt);
            }
        });
        Central2_1.add(CampoCorreo);
        CampoCorreo.setBounds(160, 260, 220, 20);

        CampoCanal.setBackground(new java.awt.Color(153, 153, 153));
        CampoCanal.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoCanal.setForeground(new java.awt.Color(102, 102, 102));
        CampoCanal.setText("Ingrese Nombre de Canal");
        CampoCanal.setBorder(null);
        CampoCanal.setNextFocusableComponent(CampoDescripcion);
        CampoCanal.setOpaque(false);
        CampoCanal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoCanalFocusGained(evt);
            }
        });
        Central2_1.add(CampoCanal);
        CampoCanal.setBounds(450, 130, 260, 20);

        CampoImagen.setBackground(new java.awt.Color(153, 153, 153));
        CampoImagen.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoImagen.setForeground(new java.awt.Color(102, 102, 102));
        CampoImagen.setText("Imágen seleccionada");
        CampoImagen.setEditable(false);
        CampoImagen.setBorder(null);
        CampoImagen.setOpaque(false);
        Central2_1.add(CampoImagen);
        CampoImagen.setBounds(390, 430, 260, 20);
        Central2_1.add(DateChoose);
        DateChoose.setBounds(220, 370, 150, 20);

        AgregarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_img.png"))); // NOI18N
        AgregarFoto.setBorderPainted(false);
        AgregarFoto.setContentAreaFilled(false);
        AgregarFoto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_img2.png"))); // NOI18N
        AgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFotoActionPerformed(evt);
            }
        });
        Central2_1.add(AgregarFoto);
        AgregarFoto.setBounds(340, 420, 40, 35);

        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_regist_2.png"))); // NOI18N
        Registrar.setBorderPainted(false);
        Registrar.setContentAreaFilled(false);
        Registrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_regist_1.png"))); // NOI18N
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        Central2_1.add(Registrar);
        Registrar.setBounds(290, 480, 110, 60);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back2.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Central2_1.add(BackButton);
        BackButton.setBounds(10, 10, 60, 50);
        Central2_1.add(CheckboxPrivado);
        CheckboxPrivado.setBounds(690, 180, 20, 20);

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator8);
        jSeparator8.setBounds(390, 450, 260, 30);

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator3);
        jSeparator3.setBounds(160, 200, 220, 30);

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator4);
        jSeparator4.setBounds(160, 240, 220, 30);

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Central2_1.add(jSeparator2);
        jSeparator2.setBounds(400, 20, 30, 370);

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator5);
        jSeparator5.setBounds(80, 60, 240, 30);

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator6);
        jSeparator6.setBounds(160, 280, 220, 30);

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator7);
        jSeparator7.setBounds(80, 350, 260, 30);

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator9);
        jSeparator9.setBounds(450, 150, 260, 30);

        jSeparator10.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator10);
        jSeparator10.setBounds(160, 160, 220, 30);

        jSeparator11.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator11);
        jSeparator11.setBounds(160, 120, 220, 30);

        jSeparator12.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator12);
        jSeparator12.setBounds(450, 60, 240, 30);

        CampoDescripcion.setColumns(20);
        CampoDescripcion.setRows(5);
        ScroolDescripcion.setViewportView(CampoDescripcion);

        Central2_1.add(ScroolDescripcion);
        ScroolDescripcion.setBounds(450, 250, 220, 80);

        Panel_Central.add(Central2_1);
        Central2_1.setBounds(0, 0, 720, 550);

        Central2_2.setLayout(null);

        comboConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConsultaActionPerformed(evt);
            }
        });
        Central2_2.add(comboConsulta);
        comboConsulta.setBounds(122, 90, 456, 22);

        BackButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        BackButton3.setBorder(null);
        BackButton3.setBorderPainted(false);
        BackButton3.setContentAreaFilled(false);
        BackButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back2.png"))); // NOI18N
        BackButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton3ActionPerformed(evt);
            }
        });
        Central2_2.add(BackButton3);
        BackButton3.setBounds(0, 11, 101, 51);

        SeleccionarUsuario.setText("Seleccionar");
        SeleccionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarUsuarioActionPerformed(evt);
            }
        });
        Central2_2.add(SeleccionarUsuario);
        SeleccionarUsuario.setBounds(596, 90, 89, 23);

        Central2_2_Panel.setMaximumSize(new java.awt.Dimension(403, 550));
        Central2_2_Panel.setMinimumSize(new java.awt.Dimension(403, 550));

        javax.swing.GroupLayout Central2_2_PanelLayout = new javax.swing.GroupLayout(Central2_2_Panel);
        Central2_2_Panel.setLayout(Central2_2_PanelLayout);
        Central2_2_PanelLayout.setHorizontalGroup(
            Central2_2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        Central2_2_PanelLayout.setVerticalGroup(
            Central2_2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        Central2_2.add(Central2_2_Panel);
        Central2_2_Panel.setBounds(0, 190, 750, 360);

        jSeparator18.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator18.setForeground(new java.awt.Color(153, 153, 153));
        Central2_2.add(jSeparator18);
        jSeparator18.setBounds(30, 160, 675, 60);

        Panel_Central.add(Central2_2);
        Central2_2.setBounds(0, 0, 720, 550);

        comboLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListaActionPerformed(evt);
            }
        });

        BackButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        BackButton2.setBorder(null);
        BackButton2.setBorderPainted(false);
        BackButton2.setContentAreaFilled(false);
        BackButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back2.png"))); // NOI18N
        BackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Central2_4Layout = new javax.swing.GroupLayout(Central2_4);
        Central2_4.setLayout(Central2_4Layout);
        Central2_4Layout.setHorizontalGroup(
            Central2_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central2_4Layout.createSequentialGroup()
                .addComponent(BackButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Central2_4Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(comboLista, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        Central2_4Layout.setVerticalGroup(
            Central2_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Central2_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton2)
                .addGap(36, 36, 36)
                .addComponent(comboLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );

        Panel_Central.add(Central2_4);
        Central2_4.setBounds(0, 0, 720, 550);

        Central2_2_1.setMaximumSize(new java.awt.Dimension(403, 550));
        Central2_2_1.setMinimumSize(new java.awt.Dimension(403, 550));
        Central2_2_1.setPreferredSize(new java.awt.Dimension(403, 550));
        Central2_2_1.setLayout(null);

        nombre.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setText("Nombre");
        Central2_2_1.add(nombre);
        nombre.setBounds(280, 80, 70, 15);

        apellido.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        apellido.setForeground(new java.awt.Color(102, 102, 102));
        apellido.setText("Apellido");
        Central2_2_1.add(apellido);
        apellido.setBounds(280, 120, 70, 15);

        nick.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        nick.setForeground(new java.awt.Color(102, 102, 102));
        nick.setText("Nickname");
        Central2_2_1.add(nick);
        nick.setBounds(280, 40, 70, 15);

        fecha.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        fecha.setForeground(new java.awt.Color(102, 102, 102));
        fecha.setText("Fecha de nacimiento");
        Central2_2_1.add(fecha);
        fecha.setBounds(280, 160, 130, 15);

        Varnick.setEditable(false);
        Varnick.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        Varnick.setBorder(null);
        Central2_2_1.add(Varnick);
        Varnick.setBounds(420, 40, 190, 15);

        mail.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        mail.setForeground(new java.awt.Color(102, 102, 102));
        mail.setText("Correo electronico");
        Central2_2_1.add(mail);
        mail.setBounds(280, 200, 120, 15);

        Varnom.setEditable(false);
        Varnom.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        Varnom.setBorder(null);
        Central2_2_1.add(Varnom);
        Varnom.setBounds(420, 80, 190, 15);

        Varape.setEditable(false);
        Varape.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        Varape.setBorder(null);
        Central2_2_1.add(Varape);
        Varape.setBounds(420, 120, 190, 15);

        Varfech.setEditable(false);
        Varfech.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        Varfech.setBorder(null);
        Central2_2_1.add(Varfech);
        Varfech.setBounds(420, 160, 190, 15);

        Varmail.setEditable(false);
        Varmail.setFont(new java.awt.Font("Manjari", 1, 12)); // NOI18N
        Varmail.setBorder(null);
        Central2_2_1.add(Varmail);
        Varmail.setBounds(420, 200, 190, 15);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        Central2_2_1.add(jSeparator1);
        jSeparator1.setBounds(280, 60, 330, 16);

        jSeparator13.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator13.setForeground(new java.awt.Color(153, 153, 153));
        Central2_2_1.add(jSeparator13);
        jSeparator13.setBounds(280, 100, 330, 16);

        jSeparator14.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator14.setForeground(new java.awt.Color(153, 153, 153));
        Central2_2_1.add(jSeparator14);
        jSeparator14.setBounds(280, 140, 330, 16);

        jSeparator15.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator15.setForeground(new java.awt.Color(153, 153, 153));
        Central2_2_1.add(jSeparator15);
        jSeparator15.setBounds(280, 220, 330, 16);
        Central2_2_1.add(jSeparator16);
        jSeparator16.setBounds(196, 94, 0, 254);

        Imagen.setBackground(new java.awt.Color(255, 255, 255));
        Imagen.setForeground(new java.awt.Color(255, 255, 255));
        Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        Imagen.setMaximumSize(new java.awt.Dimension(160, 160));
        Imagen.setMinimumSize(new java.awt.Dimension(160, 160));
        Central2_2_1.add(Imagen);
        Imagen.setBounds(80, 40, 150, 140);

        jSeparator17.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator17.setForeground(new java.awt.Color(153, 153, 153));
        Central2_2_1.add(jSeparator17);
        jSeparator17.setBounds(280, 180, 330, 16);

        Panel_Central.add(Central2_2_1);
        Central2_2_1.setBounds(0, 0, 720, 350);

        getContentPane().add(Panel_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 720, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InicioMousePressed
        // TODO add your handling code here:
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Playlist,btn_Usuario,btn_Video,btn_CerrarSesion,btn_Categorias}, new JPanel[]{ind_2,ind_3,ind_4,ind_5,ind_6});
        Panel_Central.removeAll();
        Panel_Central.add(Central1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        
    }//GEN-LAST:event_btn_InicioMousePressed

    private void btn_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UsuarioMousePressed
        // TODO add your handling code here:
         setColor(btn_Usuario); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_Playlist,btn_Inicio,btn_Video,btn_CerrarSesion,btn_Categorias}, new JPanel[]{ind_2,ind_1,ind_4,ind_5,ind_6});
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_UsuarioMousePressed

    private void btn_VideoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VideoMousePressed
        // TODO add your handling code here:
          setColor(btn_Video); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_Playlist,btn_Usuario,btn_Inicio,btn_CerrarSesion,btn_Categorias}, new JPanel[]{ind_2,ind_3,ind_1,ind_5,ind_6});
        Panel_Central.removeAll();
        Panel_Central.add(Central3);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_VideoMousePressed

    int xx,xy;
    private void Barra_SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Barra_SuperiorMousePressed

    private void Barra_SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_Barra_SuperiorMouseDragged

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        setState(Menu.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void btn_CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarSesionMousePressed
        btn_CerrarSesion.setBackground(new Color(235,76,76));
        ind_5.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Usuario,btn_Video,btn_Playlist,btn_Categorias}, new JPanel[]{ind_1,ind_3,ind_4,ind_2,ind_6});
        VentanaEmergente2 error = new VentanaEmergente2(this, rootPaneCheckingEnabled,this);
        error.setVisible(true);
    }//GEN-LAST:event_btn_CerrarSesionMousePressed

    private void btn_PlaylistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PlaylistMousePressed
        setColor(btn_Playlist); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Usuario,btn_Video,btn_CerrarSesion,btn_Categorias}, new JPanel[]{ind_1,ind_3,ind_4,ind_5,ind_6});
        Panel_Central.removeAll();
        Panel_Central.add(Scroll4);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_PlaylistMousePressed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2_1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void CampoCanalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoCanalFocusGained
        CampoCanal.setText("");
    }//GEN-LAST:event_CampoCanalFocusGained

    private void CampoCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoCorreoFocusGained
        CampoCorreo.setText("");
    }//GEN-LAST:event_CampoCorreoFocusGained

    private void CampoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoApellidoFocusGained
        CampoApellido.setText("");
    }//GEN-LAST:event_CampoApellidoFocusGained

    private void CampoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNombreFocusGained
        CampoNombre.setText("");
    }//GEN-LAST:event_CampoNombreFocusGained

    private void CampoNicknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNicknameFocusGained
        CampoNickname.setText("");
    }//GEN-LAST:event_CampoNicknameFocusGained

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUsuarioActionPerformed

    private void ListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuariosActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2_4);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        List lista = u.listaUsuarios();
        DtUsuario user;
        for(int x=0; x<=lista.size()-1; x++){
           if(lista.get(x) != null){
               user = (DtUsuario) lista.get(x);
               comboLista.addItem(user.getNickname());
            }
        }
    }//GEN-LAST:event_ListarUsuariosActionPerformed

    private void ConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarUsuariosActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2_2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        List lista = u.listaUsuarios();
        if (lista != null) {
            DtUsuario user;
            for (int x = 0; x <= lista.size() - 1; x++) {
                if (lista.get(x) != null) {
                    user = (DtUsuario) lista.get(x);
                    comboConsulta.addItem(user.getNickname());
                }
            }
        } else {
            VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
            error.CambioTexto("No existen usuarios en la base de datos.");
            error.setVisible(true);
        }
    }//GEN-LAST:event_ConsultarUsuariosActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
       String nickname = CampoNickname.getText();
       String contraseña = CampoContraseña.getText();
       String nombre = CampoNombre.getText();
       String apellido = CampoApellido.getText();
       String correo = CampoCorreo.getText();
       Boolean privado = CheckboxPrivado.getState();
       Date fecha = DateChoose.getDate();
       String nombreCanal = CampoCanal.getText();
       String descripcion = CampoDescripcion.getText();
       if(nombreCanal.isBlank())
         nombreCanal = nickname;
       if(nickname.isBlank() || contraseña.isBlank() || nombre.isBlank() || apellido.isBlank() || correo.isBlank() || fecha.toString().isBlank() || descripcion.isBlank()){
            VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
            error.CambioTexto("Debes llenar todos los campos obligatorios");
            error.setVisible(true);
       }
       else{
        rutaImagen = "/imagenesUsuarios/" + CampoNickname.getText() + ".png";
        DtCanal addCanal = new DtCanal(nombreCanal, descripcion, privado);
        DtUsuario addUser;
       
         try {
             addUser = new DtUsuario(nickname,contraseña,nombre,apellido,correo,fecha,rutaImagen);
             u.registrarUsuario(addUser, addCanal, imagen);
         } catch (UsuarioRepetidoException ex) {
             VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled);
             error.CambioTexto("El nickname o email ya existe");
             error.setVisible(true);
         }
       }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void AgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFotoActionPerformed
        SeleccionarImagen seleccionar = new SeleccionarImagen(this);
        seleccionar.setVisible(true);
    }//GEN-LAST:event_AgregarFotoActionPerformed

    private void CampoContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoContraseñaFocusGained
        CampoContraseña.setText("");
    }//GEN-LAST:event_CampoContraseñaFocusGained

    private void agrVid_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrVid_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agrVid_ButtonActionPerformed

    private void consVid_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consVid_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consVid_ButtonActionPerformed

    private void modVid_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modVid_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modVid_ButtonActionPerformed

    private void btn_CategoriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CategoriasMousePressed
        setColor(btn_Categorias); 
        ind_6.setOpaque(true);
        resetColor(new JPanel[]{btn_Usuario,btn_Playlist,btn_Inicio,btn_Video,btn_CerrarSesion,}, new JPanel[]{ind_3,ind_2,ind_1,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central5);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_CategoriasMousePressed

    private void consultaPlaylist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPlaylist_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaPlaylist_buttonActionPerformed

    private void comboListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListaActionPerformed

    }//GEN-LAST:event_comboListaActionPerformed

    private void BackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton2ActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        comboLista.removeAllItems();
    }//GEN-LAST:event_BackButton2ActionPerformed

    private void comboConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboConsultaActionPerformed

    private void BackButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton3ActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        comboLista.removeAllItems();
    }//GEN-LAST:event_BackButton3ActionPerformed

    private void SeleccionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarUsuarioActionPerformed
        Item = comboConsulta.getSelectedItem().toString();
        Central2_2_Panel.add(Central2_2_1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        List lista = u.listaUsuarios();
        DtUsuario user;
        for(int x=0; x<=lista.size()-1; x++){
            user = (DtUsuario) lista.get(x);
            if(Item.equals(user.getNickname())){
               this.Varnick.setText(Item);
               this.Varnom.setText(user.getNombre());
               this.Varape.setText(user.getApellido());
               this.Varfech.setText(user.getFechaNac().toString());
               this.Varmail.setText(user.getEmail());
            }
        }                        
        
    }//GEN-LAST:event_SeleccionarUsuarioActionPerformed

    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(114, 114, 114));
    }
   
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(73,73,73));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    
    public void SetAdmin(String texto){
        AdminChange.setText(texto);
    }
    
     public void setPathImagen(String texto, BufferedImage imagen){
        CampoImagen.setText(texto);
        this.imagen = imagen;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminChange;
    private javax.swing.JLabel AdministradorText;
    private javax.swing.JButton AgregarFoto;
    private javax.swing.JLabel AgregarImg;
    private javax.swing.JLabel AgregarUserText;
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BackButton2;
    private javax.swing.JButton BackButton3;
    private javax.swing.JPanel Barra_Superior;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JTextField CampoCanal;
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextArea CampoDescripcion;
    private javax.swing.JTextField CampoImagen;
    private javax.swing.JTextField CampoNickname;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JLabel Canal;
    private javax.swing.JPanel Central1;
    private javax.swing.JPanel Central2;
    private javax.swing.JPanel Central2_1;
    private javax.swing.JPanel Central2_2;
    private javax.swing.JPanel Central2_2_1;
    private javax.swing.JPanel Central2_2_Panel;
    private javax.swing.JPanel Central2_4;
    private javax.swing.JPanel Central3;
    private javax.swing.JPanel Central4;
    private javax.swing.JPanel Central5;
    private java.awt.Checkbox CheckboxPrivado;
    private javax.swing.JButton ConsultarUsuarios;
    private javax.swing.JLabel ConsultarUsuariosText;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Correo;
    private com.toedter.calendar.JDateChooser DateChoose;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel FechaNac;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton ListarUsuarios;
    private javax.swing.JLabel ListarUsuariosText;
    private javax.swing.JButton ModificarUsuario;
    private javax.swing.JLabel ModificarUsuarioText;
    private javax.swing.JLabel Nickname;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreCanal;
    private javax.swing.JPanel Panel_Central;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JLabel Privado;
    private javax.swing.JButton Registrar;
    private javax.swing.JScrollPane Scroll4;
    private javax.swing.JScrollPane ScroolDescripcion;
    private javax.swing.JButton SeleccionarUsuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel UsuarioBarra;
    private javax.swing.JTextField Varape;
    private javax.swing.JTextField Varfech;
    private javax.swing.JTextField Varmail;
    private javax.swing.JTextField Varnick;
    private javax.swing.JTextField Varnom;
    private javax.swing.JButton agrVid_Button;
    private javax.swing.JLabel agregarCat;
    private javax.swing.JButton agregarCat_Button;
    private javax.swing.JLabel agregarVid;
    private javax.swing.JLabel agregarVid3;
    private javax.swing.JLabel agregarVideo;
    private javax.swing.JButton agregarVideo_Button;
    private javax.swing.JLabel apellido;
    private javax.swing.JPanel btn_Categorias;
    private javax.swing.JPanel btn_CerrarSesion;
    private javax.swing.JPanel btn_Inicio;
    private javax.swing.JPanel btn_Playlist;
    private javax.swing.JPanel btn_Usuario;
    private javax.swing.JPanel btn_Video;
    private javax.swing.JButton cerrar;
    private javax.swing.JComboBox<String> comboConsulta;
    private javax.swing.JComboBox<String> comboLista;
    private javax.swing.JButton consVid_Button;
    private javax.swing.JLabel consultaCat;
    private javax.swing.JButton consultaCat_Button;
    private javax.swing.JLabel consultaPlaylist;
    private javax.swing.JButton consultaPlaylist_button;
    private javax.swing.JLabel consultaVid;
    private javax.swing.JLabel crearPlaylist;
    private javax.swing.JButton crearPlaylist_Button;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JPanel ind_6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel listarCat;
    private javax.swing.JButton listarCat_Button;
    private javax.swing.JLabel mail;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton modVid_Button;
    private javax.swing.JLabel modificarPlaylist;
    private javax.swing.JButton modificarPlaylist_Button;
    private javax.swing.JLabel modificarVid;
    private javax.swing.JLabel nick;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel quitarVideo;
    private javax.swing.JButton quitarVideo_Button;
    // End of variables declaration//GEN-END:variables
}
