/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import DataTypes.DtUsuario;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public MenuInicio() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoAPP.png")));
        setLocationRelativeTo(null);
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Usuario,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Lateral = new javax.swing.JPanel();
        btn_Inicio = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_Usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        btn_Consultas = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_Modificar = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_CerrarSesion = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Barra_Superior = new javax.swing.JPanel();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        AdministradorText = new javax.swing.JLabel();
        AdminChange = new javax.swing.JLabel();
        Panel_Central = new javax.swing.JPanel();
        Central1 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        Central2 = new javax.swing.JPanel();
        ConsultarUsuariosText = new javax.swing.JLabel();
        ListarUsuariosText = new javax.swing.JLabel();
        ModificarUsuarioText = new javax.swing.JLabel();
        AgregarUserText = new javax.swing.JLabel();
        AgregarUsuario = new javax.swing.JButton();
        ModificarUsuario = new javax.swing.JButton();
        ListarUsuarios = new javax.swing.JButton();
        ConsultarUsuarios = new javax.swing.JButton();
        Central3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Central4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Central2_1 = new javax.swing.JPanel();
        Nickname = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        FechaNac = new javax.swing.JLabel();
        Privado = new javax.swing.JLabel();
        NombreCanal = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        AgregarImg = new javax.swing.JLabel();
        CampoNickname = new javax.swing.JTextField();
        CampoNombre = new javax.swing.JTextField();
        CampoApellido = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        CampoCanal = new javax.swing.JTextField();
        DateChoose = new com.toedter.calendar.JDateChooser();
        AgregarFoto = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        CheckboxPrivado = new java.awt.Checkbox();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        ScroolDescripcion = new javax.swing.JScrollPane();
        CampoDescripcion = new javax.swing.JTextArea();
        BackButton = new javax.swing.JButton();
        CampoImagen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(73, 73, 73));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Inicio.setBackground(new java.awt.Color(73, 73, 73));
        btn_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InicioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");

        javax.swing.GroupLayout btn_InicioLayout = new javax.swing.GroupLayout(btn_Inicio);
        btn_Inicio.setLayout(btn_InicioLayout);
        btn_InicioLayout.setHorizontalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        btn_InicioLayout.setVerticalGroup(
            btn_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, -1));

        btn_Usuario.setBackground(new java.awt.Color(73, 73, 73));
        btn_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_UsuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        Usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");

        javax.swing.GroupLayout btn_UsuarioLayout = new javax.swing.GroupLayout(btn_Usuario);
        btn_Usuario.setLayout(btn_UsuarioLayout);
        btn_UsuarioLayout.setHorizontalGroup(
            btn_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Usuario)
                .addGap(0, 78, Short.MAX_VALUE))
        );
        btn_UsuarioLayout.setVerticalGroup(
            btn_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, -1));

        btn_Consultas.setBackground(new java.awt.Color(73, 73, 73));
        btn_Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ConsultasMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Consultas");

        javax.swing.GroupLayout btn_ConsultasLayout = new javax.swing.GroupLayout(btn_Consultas);
        btn_Consultas.setLayout(btn_ConsultasLayout);
        btn_ConsultasLayout.setHorizontalGroup(
            btn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        btn_ConsultasLayout.setVerticalGroup(
            btn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_ConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, -1));

        btn_Modificar.setBackground(new java.awt.Color(73, 73, 73));
        btn_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ModificarMousePressed(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modificar");

        javax.swing.GroupLayout btn_ModificarLayout = new javax.swing.GroupLayout(btn_Modificar);
        btn_Modificar.setLayout(btn_ModificarLayout);
        btn_ModificarLayout.setHorizontalGroup(
            btn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        btn_ModificarLayout.setVerticalGroup(
            btn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, -1));

        btn_CerrarSesion.setBackground(new java.awt.Color(73, 73, 73));
        btn_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CerrarSesionMousePressed(evt);
            }
        });

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cerrar Sesión");

        javax.swing.GroupLayout btn_CerrarSesionLayout = new javax.swing.GroupLayout(btn_CerrarSesion);
        btn_CerrarSesion.setLayout(btn_CerrarSesionLayout);
        btn_CerrarSesionLayout.setHorizontalGroup(
            btn_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        btn_CerrarSesionLayout.setVerticalGroup(
            btn_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_CerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Lateral.add(btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, -1));

        getContentPane().add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 590));

        Barra_Superior.setBackground(new java.awt.Color(12, 129, 129));
        Barra_Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMouseDragged(evt);
            }
        });
        Barra_Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_SuperiorMousePressed(evt);
            }
        });
        Barra_Superior.setLayout(null);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar2.png"))); // NOI18N
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        Barra_Superior.add(minimizar);
        minimizar.setBounds(660, 10, 20, 20);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar2.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        Barra_Superior.add(cerrar);
        cerrar.setBounds(690, 10, 20, 20);

        AdministradorText.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        AdministradorText.setForeground(new java.awt.Color(255, 255, 255));
        AdministradorText.setText("Administrador: ");
        Barra_Superior.add(AdministradorText);
        AdministradorText.setBounds(20, 10, 130, 20);

        AdminChange.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        AdminChange.setForeground(new java.awt.Color(255, 255, 255));
        Barra_Superior.add(AdminChange);
        AdminChange.setBounds(120, 10, 140, 20);

        getContentPane().add(Barra_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 40));

        Panel_Central.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Central.setLayout(null);

        Central1.setLayout(null);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoHome.gif"))); // NOI18N
        Central1.add(fondo);
        fondo.setBounds(0, 0, 720, 550);

        Panel_Central.add(Central1);
        Central1.setBounds(0, 0, 720, 550);

        Central2.setForeground(new java.awt.Color(255, 255, 255));
        Central2.setLayout(null);

        ConsultarUsuariosText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConsultarUsuariosText.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarUsuariosText.setText("Consultar Usuario");
        Central2.add(ConsultarUsuariosText);
        ConsultarUsuariosText.setBounds(460, 50, 130, 20);

        ListarUsuariosText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListarUsuariosText.setForeground(new java.awt.Color(255, 255, 255));
        ListarUsuariosText.setText("Listar Usuarios");
        Central2.add(ListarUsuariosText);
        ListarUsuariosText.setBounds(470, 300, 120, 20);

        ModificarUsuarioText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModificarUsuarioText.setForeground(new java.awt.Color(255, 255, 255));
        ModificarUsuarioText.setText("Modificar Usuario");
        Central2.add(ModificarUsuarioText);
        ModificarUsuarioText.setBounds(160, 300, 130, 20);

        AgregarUserText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AgregarUserText.setForeground(new java.awt.Color(255, 255, 255));
        AgregarUserText.setText("Agregar Usuario");
        Central2.add(AgregarUserText);
        AgregarUserText.setBounds(160, 50, 120, 20);

        AgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarUser.png"))); // NOI18N
        AgregarUsuario.setBorderPainted(false);
        AgregarUsuario.setContentAreaFilled(false);
        AgregarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarUser2.png"))); // NOI18N
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });
        Central2.add(AgregarUsuario);
        AgregarUsuario.setBounds(90, 40, 243, 221);
        AgregarUsuario.getAccessibleContext().setAccessibleName("AgregarUsuario");

        ModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarUser.png"))); // NOI18N
        ModificarUsuario.setBorderPainted(false);
        ModificarUsuario.setContentAreaFilled(false);
        ModificarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarUser2.png"))); // NOI18N
        ModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioActionPerformed(evt);
            }
        });
        Central2.add(ModificarUsuario);
        ModificarUsuario.setBounds(90, 290, 243, 221);

        ListarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Listar.png"))); // NOI18N
        ListarUsuarios.setBorderPainted(false);
        ListarUsuarios.setContentAreaFilled(false);
        ListarUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Listar2.png"))); // NOI18N
        ListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuariosActionPerformed(evt);
            }
        });
        Central2.add(ListarUsuarios);
        ListarUsuarios.setBounds(390, 290, 243, 221);

        ConsultarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarUser.png"))); // NOI18N
        ConsultarUsuarios.setBorderPainted(false);
        ConsultarUsuarios.setContentAreaFilled(false);
        ConsultarUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarUser2.png"))); // NOI18N
        ConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarUsuariosActionPerformed(evt);
            }
        });
        Central2.add(ConsultarUsuarios);
        ConsultarUsuarios.setBounds(390, 40, 243, 221);

        Panel_Central.add(Central2);
        Central2.setBounds(0, 0, 720, 550);

        Central3.setLayout(null);

        jLabel3.setText("PANEL CONSULTAS");
        Central3.add(jLabel3);
        jLabel3.setBounds(307, 225, 107, 29);

        Panel_Central.add(Central3);
        Central3.setBounds(0, 0, 720, 550);

        Central4.setLayout(null);

        jLabel4.setText("PANEL MODIFICAR");
        Central4.add(jLabel4);
        jLabel4.setBounds(310, 227, 149, 29);

        Panel_Central.add(Central4);
        Central4.setBounds(0, 0, 720, 550);

        Central2_1.setMinimumSize(new java.awt.Dimension(720, 560));
        Central2_1.setLayout(null);

        Nickname.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Nickname.setText("Nickname(*)");
        Central2_1.add(Nickname);
        Nickname.setBounds(180, 30, 110, 14);

        Nombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Nombre.setText("Nombre(*)");
        Central2_1.add(Nombre);
        Nombre.setBounds(180, 70, 110, 14);

        Apellido.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Apellido.setText("Apellido(*)");
        Central2_1.add(Apellido);
        Apellido.setBounds(180, 110, 110, 14);

        Correo.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Correo.setText("Correo(*)");
        Central2_1.add(Correo);
        Correo.setBounds(180, 150, 110, 14);

        FechaNac.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        FechaNac.setText("Fecha de nacimiento(*)");
        Central2_1.add(FechaNac);
        FechaNac.setBounds(180, 250, 180, 14);

        Privado.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Privado.setText("¿Desea hacer el canal privado?");
        Central2_1.add(Privado);
        Privado.setBounds(180, 190, 230, 19);

        NombreCanal.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        NombreCanal.setText("Nombre de su canal(opcional)");
        Central2_1.add(NombreCanal);
        NombreCanal.setBounds(180, 290, 220, 20);

        Descripcion.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Descripcion.setText("Descripcion de canal(*)");
        Central2_1.add(Descripcion);
        Descripcion.setBounds(180, 320, 160, 40);

        AgregarImg.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        AgregarImg.setText("Agregar imágen(opcional)");
        Central2_1.add(AgregarImg);
        AgregarImg.setBounds(160, 430, 190, 30);

        CampoNickname.setBackground(new java.awt.Color(153, 153, 153));
        CampoNickname.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        CampoNickname.setForeground(new java.awt.Color(102, 102, 102));
        CampoNickname.setText("Ingrese Nickname");
        CampoNickname.setBorder(null);
        CampoNickname.setOpaque(false);
        CampoNickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNicknameFocusGained(evt);
            }
        });
        Central2_1.add(CampoNickname);
        CampoNickname.setBounds(290, 30, 260, 14);

        CampoNombre.setBackground(new java.awt.Color(153, 153, 153));
        CampoNombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        CampoNombre.setForeground(new java.awt.Color(102, 102, 102));
        CampoNombre.setText("Ingrese Nombre");
        CampoNombre.setBorder(null);
        CampoNombre.setOpaque(false);
        CampoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNombreFocusGained(evt);
            }
        });
        Central2_1.add(CampoNombre);
        CampoNombre.setBounds(290, 70, 260, 14);

        CampoApellido.setBackground(new java.awt.Color(153, 153, 153));
        CampoApellido.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        CampoApellido.setForeground(new java.awt.Color(102, 102, 102));
        CampoApellido.setText("Ingrese Apellido");
        CampoApellido.setBorder(null);
        CampoApellido.setOpaque(false);
        CampoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoApellidoFocusGained(evt);
            }
        });
        Central2_1.add(CampoApellido);
        CampoApellido.setBounds(290, 110, 260, 14);

        CampoCorreo.setBackground(new java.awt.Color(153, 153, 153));
        CampoCorreo.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        CampoCorreo.setForeground(new java.awt.Color(102, 102, 102));
        CampoCorreo.setText("Ingrese Correo");
        CampoCorreo.setBorder(null);
        CampoCorreo.setOpaque(false);
        CampoCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoCorreoFocusGained(evt);
            }
        });
        Central2_1.add(CampoCorreo);
        CampoCorreo.setBounds(290, 150, 260, 14);

        CampoCanal.setBackground(new java.awt.Color(153, 153, 153));
        CampoCanal.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        CampoCanal.setForeground(new java.awt.Color(102, 102, 102));
        CampoCanal.setText("Ingrese Nombre de Canal");
        CampoCanal.setBorder(null);
        CampoCanal.setOpaque(false);
        CampoCanal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoCanalFocusGained(evt);
            }
        });
        Central2_1.add(CampoCanal);
        CampoCanal.setBounds(400, 290, 260, 14);
        Central2_1.add(DateChoose);
        DateChoose.setBounds(360, 250, 190, 20);

        AgregarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_img.png"))); // NOI18N
        AgregarFoto.setBorderPainted(false);
        AgregarFoto.setContentAreaFilled(false);
        AgregarFoto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_img2.png"))); // NOI18N
        AgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFotoActionPerformed(evt);
            }
        });
        Central2_1.add(AgregarFoto);
        AgregarFoto.setBounds(340, 430, 40, 35);

        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_regist_2.png"))); // NOI18N
        Registrar.setBorderPainted(false);
        Registrar.setContentAreaFilled(false);
        Registrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_regist_1.png"))); // NOI18N
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        Central2_1.add(Registrar);
        Registrar.setBounds(290, 480, 110, 60);
        Central2_1.add(CheckboxPrivado);
        CheckboxPrivado.setBounds(420, 190, 20, 20);

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator8);
        jSeparator8.setBounds(400, 460, 260, 30);

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator3);
        jSeparator3.setBounds(290, 90, 260, 30);

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator4);
        jSeparator4.setBounds(290, 130, 260, 30);

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator2);
        jSeparator2.setBounds(180, 230, 370, 30);

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator5);
        jSeparator5.setBounds(290, 50, 260, 30);

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator6);
        jSeparator6.setBounds(290, 170, 260, 30);

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        Central2_1.add(jSeparator7);
        jSeparator7.setBounds(400, 310, 260, 30);

        CampoDescripcion.setColumns(20);
        CampoDescripcion.setRows(5);
        ScroolDescripcion.setViewportView(CampoDescripcion);

        Central2_1.add(ScroolDescripcion);
        ScroolDescripcion.setBounds(360, 330, 220, 80);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back2.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Central2_1.add(BackButton);
        BackButton.setBounds(30, 20, 60, 50);

        CampoImagen.setBackground(new java.awt.Color(153, 153, 153));
        CampoImagen.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        CampoImagen.setForeground(new java.awt.Color(102, 102, 102));
        CampoImagen.setText("Imágen seleccionada");
        CampoImagen.setBorder(null);
        CampoImagen.setOpaque(false);
        Central2_1.add(CampoImagen);
        CampoImagen.setBounds(400, 440, 260, 20);

        Panel_Central.add(Central2_1);
        Central2_1.setBounds(0, 0, 720, 550);

        getContentPane().add(Panel_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 720, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InicioMousePressed
        // TODO add your handling code here:
        setColor(btn_Inicio); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Usuario,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
        
    }//GEN-LAST:event_btn_InicioMousePressed

    private void btn_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UsuarioMousePressed
        // TODO add your handling code here:
         setColor(btn_Usuario); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Inicio,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_2,ind_1,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_UsuarioMousePressed

    private void btn_ConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultasMousePressed
        // TODO add your handling code here:
          setColor(btn_Consultas); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_Modificar,btn_Usuario,btn_Inicio,btn_CerrarSesion}, new JPanel[]{ind_2,ind_3,ind_1,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central3);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_ConsultasMousePressed

    int xx,xy;
    private void Barra_SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Barra_SuperiorMousePressed

    private void Barra_SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_SuperiorMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_Barra_SuperiorMouseDragged

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        setState(Menu.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void btn_CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarSesionMousePressed
        btn_CerrarSesion.setBackground(new Color(235,76,76));
        ind_5.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Usuario,btn_Consultas,btn_Modificar}, new JPanel[]{ind_1,ind_3,ind_4,ind_2});
        VentanaEmergente2 error = new VentanaEmergente2(this, rootPaneCheckingEnabled,this);
        error.setVisible(true);
    }//GEN-LAST:event_btn_CerrarSesionMousePressed

    private void btn_ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModificarMousePressed
        setColor(btn_Modificar); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_Inicio,btn_Usuario,btn_Consultas,btn_CerrarSesion}, new JPanel[]{ind_1,ind_3,ind_4,ind_5});
        Panel_Central.removeAll();
        Panel_Central.add(Central4);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_btn_ModificarMousePressed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2_1);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void CampoCanalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoCanalFocusGained
        CampoCanal.setText("");
    }//GEN-LAST:event_CampoCanalFocusGained

    private void CampoCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoCorreoFocusGained
        CampoCorreo.setText("");
    }//GEN-LAST:event_CampoCorreoFocusGained

    private void CampoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoApellidoFocusGained
        CampoApellido.setText("");
    }//GEN-LAST:event_CampoApellidoFocusGained

    private void CampoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNombreFocusGained
        CampoNombre.setText("");
    }//GEN-LAST:event_CampoNombreFocusGained

    private void CampoNicknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNicknameFocusGained
        CampoNickname.setText("");
    }//GEN-LAST:event_CampoNicknameFocusGained

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Panel_Central.removeAll();
        Panel_Central.add(Central2);
        Panel_Central.revalidate();
        Panel_Central.repaint();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUsuarioActionPerformed

    private void ListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarUsuariosActionPerformed

    private void ConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarUsuariosActionPerformed

String rutaImagen;
    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
       String nickname = CampoNickname.getText();
       String nombre = CampoNombre.getText();
       String apellido = CampoApellido.getText();
       String correo = CampoCorreo.getText();
       Boolean privado = CheckboxPrivado.getState();
       Date fecha = DateChoose.getDate();
       String nombreCanal = CampoCanal.getText();
       if(nombreCanal.isBlank())
         nombreCanal = nickname;
       String descripcion = CampoDescripcion.getText();
       DtUsuario addUser = new DtUsuario(nickname,nombre,apellido,correo,fecha,rutaImagen);
       
    }//GEN-LAST:event_RegistrarActionPerformed

    private void AgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFotoActionPerformed
        SeleccionarImagen seleccionar = new SeleccionarImagen(this);
        seleccionar.setVisible(true);
    }//GEN-LAST:event_AgregarFotoActionPerformed

    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(114, 114, 114));
    }
   
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(73,73,73));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    
    public void SetAdmin(String texto){
        AdminChange.setText(texto);
    }
    
     public void setPathImagen(String texto){
         CampoImagen.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminChange;
    private javax.swing.JLabel AdministradorText;
    private javax.swing.JButton AgregarFoto;
    private javax.swing.JLabel AgregarImg;
    private javax.swing.JLabel AgregarUserText;
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Barra_Superior;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JTextField CampoCanal;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextArea CampoDescripcion;
    private javax.swing.JTextField CampoImagen;
    private javax.swing.JTextField CampoNickname;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JPanel Central1;
    private javax.swing.JPanel Central2;
    private javax.swing.JPanel Central2_1;
    private javax.swing.JPanel Central3;
    private javax.swing.JPanel Central4;
    private java.awt.Checkbox CheckboxPrivado;
    private javax.swing.JButton ConsultarUsuarios;
    private javax.swing.JLabel ConsultarUsuariosText;
    private javax.swing.JLabel Correo;
    private com.toedter.calendar.JDateChooser DateChoose;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel FechaNac;
    private javax.swing.JButton ListarUsuarios;
    private javax.swing.JLabel ListarUsuariosText;
    private javax.swing.JButton ModificarUsuario;
    private javax.swing.JLabel ModificarUsuarioText;
    private javax.swing.JLabel Nickname;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreCanal;
    private javax.swing.JPanel Panel_Central;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JLabel Privado;
    private javax.swing.JButton Registrar;
    private javax.swing.JScrollPane ScroolDescripcion;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel btn_CerrarSesion;
    private javax.swing.JPanel btn_Consultas;
    private javax.swing.JPanel btn_Inicio;
    private javax.swing.JPanel btn_Modificar;
    private javax.swing.JPanel btn_Usuario;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton minimizar;
    // End of variables declaration//GEN-END:variables
}
