/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author esteban
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    Font manjari, berlin;
    
    public Menu() {
        try {
            String path = System.getProperty("user.dir") + "/src/main/resources/font/Manjari.ttf";
            manjari = Font.createFont(Font.TRUETYPE_FONT, new File(path)).deriveFont(14f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(manjari);
            path = System.getProperty("user.dir") + "/src/main/resources/font/Berlin.ttf";
            berlin = Font.createFont(Font.TRUETYPE_FONT, new File(path)).deriveFont(16f);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoAPP.png")));
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        Panel = new javax.swing.JPanel();
        Password = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        FondoUsername = new javax.swing.JLabel();
        FondoPassword = new javax.swing.JLabel();
        InicioSesion = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        menuIniciar = new javax.swing.JButton();
        menuCancelar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        DragPanel = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaptionBorder);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Panel.setBackground(new java.awt.Color(12, 129, 129));
        Panel.setLayout(null);

        Password.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("password");
        Password.setBorder(null);
        Password.setOpaque(false);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        Panel.add(Password);
        Password.setBounds(140, 300, 290, 50);

        Username.setFont(manjari.deriveFont(18f));
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setText("Username");
        Username.setBorder(null);
        Username.setOpaque(false);
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
        });
        Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameKeyPressed(evt);
            }
        });
        Panel.add(Username);
        Username.setBounds(140, 230, 290, 50);

        FondoUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/txt_user.png"))); // NOI18N
        Panel.add(FondoUsername);
        FondoUsername.setBounds(80, 220, 340, 70);

        FondoPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/txt_pass.png"))); // NOI18N
        Panel.add(FondoPassword);
        FondoPassword.setBounds(80, 290, 340, 70);

        InicioSesion.setBackground(new java.awt.Color(247, 243, 247));
        InicioSesion.setFont(manjari.deriveFont(26f));
        InicioSesion.setForeground(new java.awt.Color(101, 13, 136));
        InicioSesion.setText("Inicio de sesión");
        Panel.add(InicioSesion);
        InicioSesion.setBounds(160, 180, 220, 40);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.setText("jLabel4");
        Panel.add(Logo);
        Logo.setBounds(150, 10, 200, 170);

        menuIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_iniciar_2.png"))); // NOI18N
        menuIniciar.setBorderPainted(false);
        menuIniciar.setContentAreaFilled(false);
        menuIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_iniciar_1.png"))); // NOI18N
        menuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarActionPerformed(evt);
            }
        });
        Panel.add(menuIniciar);
        menuIniciar.setBounds(140, 370, 100, 50);

        menuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_2.png"))); // NOI18N
        menuCancelar.setBorderPainted(false);
        menuCancelar.setContentAreaFilled(false);
        menuCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_1.png"))); // NOI18N
        menuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelarActionPerformed(evt);
            }
        });
        Panel.add(menuCancelar);
        menuCancelar.setBounds(270, 370, 100, 50);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar2.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        Panel.add(cerrar);
        cerrar.setBounds(470, 10, 20, 20);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconMinimizar2.png"))); // NOI18N
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        Panel.add(minimizar);
        minimizar.setBounds(440, 10, 20, 20);

        getContentPane().add(Panel);
        Panel.setBounds(0, 0, 500, 510);

        DragPanel.setBackground(new java.awt.Color(12, 129, 129));
        DragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragPanelMouseDragged(evt);
            }
        });
        DragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DragPanelLayout = new javax.swing.GroupLayout(DragPanel);
        DragPanel.setLayout(DragPanelLayout);
        DragPanelLayout.setHorizontalGroup(
            DragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DragPanelLayout.setVerticalGroup(
            DragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(DragPanel);
        DragPanel.setBounds(0, 0, 500, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarActionPerformed
        String nombre = Username.getText();
        if("admin".equals(nombre)){ //Usuario correcto
            MenuInicio menuinicio = new MenuInicio(manjari,berlin);
            menuinicio.setVisible(true);
            this.setVisible(false);
        }
        else{ //Usuario incorrecto
            VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled,manjari);
            
            error.CambioTexto("     Los datos ingresados son incorrectos");
            error.setVisible(true);
           
        }
    }//GEN-LAST:event_menuIniciarActionPerformed

    private void menuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelarActionPerformed
      System.exit(0);
    }//GEN-LAST:event_menuCancelarActionPerformed

    private void UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String nombre = Username.getText();
            if("admin".equals(nombre)){ //Usuario correcto
                MenuInicio menuinicio = new MenuInicio(manjari,berlin);
                menuinicio.setVisible(true);
                this.setVisible(false);
            }
            else{ //Usuario incorrecto
                VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled,manjari);
                error.CambioTexto("     Los datos ingresados son incorrectos");
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_UsernameKeyPressed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
      System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        setState(Menu.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed
int xx,xy;
    private void DragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_DragPanelMouseDragged

    private void DragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_DragPanelMousePressed

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        if(Username.getText().equals("Username"))
        Username.setText("");
    }//GEN-LAST:event_UsernameFocusGained

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
         if(Password.getText().equals("password"))
        Password.setText("");
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String nombre = Password.getText();
            if("admin".equals(nombre)){ //Usuario correcto
                MenuInicio menuinicio = new MenuInicio(manjari,berlin);
                menuinicio.setVisible(true);
                this.setVisible(false);
            }
            else{ //Usuario incorrecto
                VentanaEmergente error = new VentanaEmergente(this, rootPaneCheckingEnabled,manjari);
                error.CambioTexto("     Los datos ingresados son incorrectos");
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DragPanel;
    private javax.swing.JLabel FondoPassword;
    private javax.swing.JLabel FondoUsername;
    private javax.swing.JLabel InicioSesion;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton cerrar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton menuCancelar;
    private javax.swing.JButton menuIniciar;
    private javax.swing.JButton minimizar;
    // End of variables declaration//GEN-END:variables
}
