/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author isaac
 */
public class SeleccionarImagen extends javax.swing.JFrame {

    private final JFileChooser openFileChooser;
    private BufferedImage originalBI;
    private String direccion;
    private final MenuInicio mi;
    /**
     * Creates new form SeleccionarImagen
     * @param frame
     */
    
    public SeleccionarImagen(MenuInicio frame) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoAPP.png")));
        setLocationRelativeTo(null);
        this.mi = frame;
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("Imagenes PNG o JPG", "png", "jpg"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraSuperior = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        PanelFondo = new javax.swing.JPanel();
        AbrirArchivo = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();
        CampoFile = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Imagen1 = new javax.swing.JLabel();
        DragPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 370));
        setUndecorated(true);
        getContentPane().setLayout(null);

        BarraSuperior.setBackground(new java.awt.Color(73, 73, 73));

        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setContentAreaFilled(false);
        BotonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconCerrar2.png"))); // NOI18N
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(BarraSuperior);
        BarraSuperior.setBounds(0, 0, 400, 33);

        PanelFondo.setLayout(null);

        AbrirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_abrirarchivo_2.png"))); // NOI18N
        AbrirArchivo.setBorder(null);
        AbrirArchivo.setBorderPainted(false);
        AbrirArchivo.setContentAreaFilled(false);
        AbrirArchivo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_abrirarchivo_1.png"))); // NOI18N
        AbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirArchivoActionPerformed(evt);
            }
        });
        PanelFondo.add(AbrirArchivo);
        AbrirArchivo.setBounds(30, 50, 80, 40);

        BotonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_3.png"))); // NOI18N
        BotonCancelar.setBorder(null);
        BotonCancelar.setBorderPainted(false);
        BotonCancelar.setContentAreaFilled(false);
        BotonCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_4.png"))); // NOI18N
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonCancelar);
        BotonCancelar.setBounds(220, 310, 80, 40);

        BotonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_aceptar_2.png"))); // NOI18N
        BotonAceptar.setBorder(null);
        BotonAceptar.setBorderPainted(false);
        BotonAceptar.setContentAreaFilled(false);
        BotonAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_aceptar_1.png"))); // NOI18N
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonAceptar);
        BotonAceptar.setBounds(100, 310, 80, 40);

        CampoFile.setEditable(false);
        CampoFile.setBackground(new java.awt.Color(153, 153, 153));
        CampoFile.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        CampoFile.setForeground(new java.awt.Color(102, 102, 102));
        CampoFile.setText("Imágen seleccionada");
        CampoFile.setBorder(null);
        CampoFile.setOpaque(false);
        PanelFondo.add(CampoFile);
        CampoFile.setBounds(120, 60, 260, 20);

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        PanelFondo.add(jSeparator5);
        jSeparator5.setBounds(90, 290, 210, 30);

        jLabel1.setFont(new java.awt.Font("Manjari Bold", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Tamaño máximo 160x160");
        PanelFondo.add(jLabel1);
        jLabel1.setBounds(110, 270, 190, 20);

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        PanelFondo.add(jSeparator6);
        jSeparator6.setBounds(120, 80, 260, 30);

        Imagen1.setBackground(new java.awt.Color(255, 255, 255));
        Imagen1.setForeground(new java.awt.Color(255, 255, 255));
        Imagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        Imagen1.setMaximumSize(new java.awt.Dimension(160, 160));
        Imagen1.setMinimumSize(new java.awt.Dimension(160, 160));
        Imagen1.setPreferredSize(new java.awt.Dimension(160, 160));
        PanelFondo.add(Imagen1);
        Imagen1.setBounds(120, 100, 160, 160);

        getContentPane().add(PanelFondo);
        PanelFondo.setBounds(0, 0, 400, 370);

        DragPanel.setBackground(new java.awt.Color(12, 129, 129));
        DragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragPanelMouseDragged(evt);
            }
        });
        DragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DragPanelLayout = new javax.swing.GroupLayout(DragPanel);
        DragPanel.setLayout(DragPanelLayout);
        DragPanelLayout.setHorizontalGroup(
            DragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DragPanelLayout.setVerticalGroup(
            DragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(DragPanel);
        DragPanel.setBounds(0, 0, 400, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx, xy;
    private void DragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMouseDragged
        // TODO add your handling code here:
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_DragPanelMouseDragged

    private void DragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_DragPanelMousePressed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        mi.setPathImagen(direccion,originalBI);
        dispose();
    }//GEN-LAST:event_BotonAceptarActionPerformed
    
    private void AbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirArchivoActionPerformed
       int retorno = openFileChooser.showOpenDialog(this);
       if(retorno == JFileChooser.APPROVE_OPTION){
           try{
               originalBI = ImageIO.read(openFileChooser.getSelectedFile());
               int ancho = originalBI.getWidth();
               int alto = originalBI.getHeight();
               if(ancho>160 || alto>160){
                   CampoFile.setText("La imágen seleccionada es muy grande");
               }
               else{
                File archivo = openFileChooser.getSelectedFile();
                direccion = archivo.getAbsolutePath();
                CampoFile.setText(direccion);
                Imagen1.setIcon(new ImageIcon(direccion));
               }
           }catch(IOException ieo){
               CampoFile.setText("Archivo de formato incorrecto");
           }
       }
       else{
           direccion = "No se ha seleccionado una imágen";
           CampoFile.setText(direccion);
       }
    }//GEN-LAST:event_AbrirArchivoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirArchivo;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JTextField CampoFile;
    private javax.swing.JPanel DragPanel;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
